---
sidebar: sidebar 
permalink: concepts/licensing.html 
keywords: license, licensing 
summary: 瞭解Astra Control Center可執行的行動、會因授權狀態而異、以及Astra Control Center的使用如何影響授權使用量。 
---
= 授權
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center需要安裝授權、才能啟用完整的應用程式資料管理功能。當您部署Astra Control Center時、若無授權、Web UI會顯示橫幅、警告系統功能有限。

下列作業需要有效的授權：

* 管理新應用程式
* 建立快照或備份
* 設定保護原則以排程快照或備份
* 從快照或備份還原
* 從快照或目前狀態複製
* 將應用程式複寫到遠端系統



NOTE: 您可以新增叢集、新增資源庫、以及管理Astra Data Store儲存後端、而無需授權。不過、您需要有效的Astra Control Center授權、才能使用Astra Data Store作為儲存後端來管理應用程式。



== 如何計算授權使用量

當您將新叢集新增至Astra Control Center時、除非至少有一個執行於叢集上的應用程式由Astra Control Center管理、否則它不會將使用的授權列入計算。您也可以將Astra Data Store儲存後端新增至Astra Control Center、而不會影響授權使用量。這可讓您從未獲授權的Astra Control Center系統管理Astra Data Store後端。

當您開始管理叢集上的應用程式時、該叢集的所有CPU單元都會包含在Astra Control Center授權使用量中。如果叢集已獲授權部署Astra Data Store、則Astra Control Center授權使用量計算將排除這些CPU單元。


NOTE: Astra資料儲存區評估部署中的CPU單元、不會排除在Astra控制中心授權使用量之外。



== 如需詳細資訊、請參閱

* link:../use/update-licenses.html["更新現有授權"]

