---
sidebar: sidebar 
permalink: use/manage-packages-acc.html 
keywords: manage package, packages, install 
summary: 您可以上傳並安裝套件至Astra Control Center。 
---
= 管理軟體套件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


NetApp為Astra Control Center提供額外功能、提供您可從NetApp支援網站下載的軟體套件。連接Docker和成品儲存庫之後、您可以上傳和匯入套件、將此功能新增至Astra Control Center。您可以使用CLI或Astra Control Center Web UI來管理軟體套件。

.您需要的是 #8217 ；需要的是什麼
* Kubernetes叢集已安裝Astra Control Center
* 連線的Docker映像儲存庫、可容納軟體套件映像。如需詳細資訊、請參閱 link:manage-connections.html["管理儲存庫連線"]。
* 連線的成品儲存庫、用於儲存軟體套件二進位檔和成品。如需詳細資訊、請參閱 link:manage-connections.html["管理儲存庫連線"]。
* NetApp支援網站提供的軟體套件




== 將軟體套件映像上傳至儲存庫

Astra Control Center會參考連線儲存庫中的套件映像和成品。您可以使用CLI將影像和成品上傳至儲存庫。

.步驟
. 請從NetApp支援網站下載軟體套件、並將其儲存在已安裝「kubecll」公用程式的機器上。
. 擷取壓縮的套件檔案、並將目錄變更為Astra Control套裝組合檔案的位置（例如、「acs.manifest.bunder.yaml」）。
. 執行下列指令碼、將套件映像推送到Docker儲存庫。將"REGISTRY"變數的值取代為您自己登錄的URL：


[listing]
----
# Replace the registry value:
export REGISTRY=registry.url.com

export PACKAGENAME=astrads
export PACKAGEVERSION=22.5.0-6371157
export DIRECTORYNAME=astrads

for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
  # Remove path and keep imageName
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
  # Tag with local image repo.
  docker tag ${astraImage} ${REGISTRY}/netapp/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
  # Push to the local repo.
  docker push ${REGISTRY}/netapp/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done

export PACKAGENAME=vasa-provider
export PACKAGEVERSION=2022.5.0
export DIRECTORYNAME=vasa

for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
  # Remove path and keep imageName
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')
  # Tag with local image repo.
  docker tag ${astraImage} ${REGISTRY}/netapp/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
  # Push to the local repo.
  docker push ${REGISTRY}/netapp/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


== 新增軟體套件

您可以使用Astra Control Center套裝組合檔案匯入軟體套件。這樣做會安裝套件、讓Astra Control Center能夠使用該軟體。



=== 使用Astra Control網路UI新增軟體套件

您可以使用Astra Control Center網路UI來新增已上傳至連線儲存庫的軟體套件。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*套件*索引標籤。
. 選取*「Add*（新增*）」按鈕。
. 在檔案選擇對話方塊中、選取上傳圖示。
. 選擇要上傳的Astra Control套裝組合檔案、格式為「.yaml」。
. 選取*「Add*」。


如果套件檔案有效、且套件映像和成品位於連線的儲存庫中、則套件會新增至Astra Control Center。當「*狀態*」欄中的狀態變更為*可用*時、您可以使用套件。您可以將游標暫留在套件的狀態上、以取得更多資訊。


NOTE: 如果您的儲存庫中找不到套件的一或多個影像或成品、則會出現該套件的錯誤訊息。



=== 使用CLI新增軟體套件

您可以使用CLI匯入已上傳至連線儲存庫的軟體套件。為達成此目的、您必須先記錄Astra Control Center帳戶ID和API權杖。

.步驟
. 使用網頁瀏覽器登入Astra Control Center網頁UI。
. 從儀表板中、選取右上角的使用者圖示。
. 選擇* API存取*。
. 請記下畫面頂端附近的帳戶ID。
. 選取*產生API權杖*。
. 在產生的對話方塊中、選取*產生API權杖*。
. 記下產生的權杖、然後選取*關閉*。在CLI中、將目錄變更為擷取套件內容中的「.yaml」套件檔案位置。
. 使用套件檔案匯入套件、並進行下列替代：
+
** 以Astra Control套裝組合檔案的名稱取代bunder_file。
** 以Astra Control執行個體的DNS名稱取代伺服器。
** 使用您先前記錄的帳戶ID和API Token來取代帳戶ID和Token。
+
[listing]
----
kubectl astra packages import -m BUNDLE_FILE -u SERVER -a ACCOUNT_ID -k TOKEN
----




如果套件檔案有效、且套件映像和成品位於連線的儲存庫中、則套件會新增至Astra Control Center。


NOTE: 如果您的儲存庫中找不到套件的一或多個影像或成品、則會出現該套件的錯誤訊息。



== 移除軟體套件

您可以使用Astra Control Center網路UI移除先前匯入Astra Control Center的軟體套件。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*套件*索引標籤。
+
您可以在此頁面上查看已安裝套件的清單及其狀態。

. 在套件的「*動作*」欄中、開啟「動作」功能表。
. 選擇*刪除*。


套件會從Astra Control Center刪除、但套件的映像和成品仍會保留在儲存庫中。

[discrete]
== 如需詳細資訊、請參閱

* link:manage-connections.html["管理儲存庫連線"]

