---
sidebar: sidebar 
permalink: use/manage-remote-users-groups.html 
keywords: import, import users, search, search users, groups, import groups 
summary: 在Astra Control Center系統上管理遠端LDAP使用者和群組。 
---
= 管理遠端使用者和群組
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
如果您已在Astra Control系統上啟用LDAP驗證、您可以搜尋LDAP使用者和群組、並將其納入系統的核准使用者中。



== 新增遠端使用者

帳戶擁有者和管理員可以將遠端使用者新增至Astra Control。Astra Control Center 最多支援 10 、 000 名 LDAP 遠端使用者。


IMPORTANT: Astra Control Center 會使用啟用遠端驗證時所設定的使用者登入屬性來搜尋和追蹤遠端使用者。此欄位中必須存在電子郵件地址（「郵件」）或使用者主體名稱（「 userPrincipalName 」）的屬性、您想要在 Astra Control Center 中顯示的任何遠端使用者都必須存在。此屬性在 Astra Control Center 中作為驗證的使用者名稱、並在搜尋遠端使用者時使用。


NOTE: 如果系統上已存在具有相同電子郵件地址的本機使用者（根據「 mail 」或「 user principal name 」屬性）、則無法新增遠端使用者。若要將使用者新增為遠端使用者、請先從系統中刪除本機使用者。

.步驟
. 前往*帳戶*區域。
. 選取*使用者與群組*索引標籤。
. 在頁面最右側、選取*遠端使用者*。
. 選取*「Add*」。
. 或者、您也可以在*依電子郵件篩選*欄位中輸入使用者的電子郵件地址、以搜尋LDAP使用者。
. 從清單中選取一或多個使用者。
. 指派角色給使用者。
+

NOTE: 如果您指派不同的角色給使用者和使用者群組、則權限越高的角色優先。

. 您也可以將一或多個命名空間限制指派給此使用者、然後選取*限制角色至限制*以強制執行限制。您可以選取*新增限制*來新增命名空間限制。
+

NOTE: 當使用者透過LDAP群組成員資格指派多個角色時、最具權限角色的限制是唯一會生效的限制。例如、如果具有本機檢視器角色的使用者加入三個繫結至「成員」角色的群組、則「成員」角色的限制總和會生效、而且會忽略「檢視器」角色的任何限制。

. 選取*「Add*」。


.結果
新使用者會出現在遠端使用者清單中。在此清單中、您可以看到使用者的作用中限制、也可以從*動作*功能表管理使用者。



== 新增遠端群組

若要一次新增許多遠端使用者、帳戶擁有者和管理員可以將遠端群組新增至Astra Control。當您新增遠端群組時、該群組中的所有遠端使用者都可以登入 Astra Control 、並繼承與該群組相同的角色。

Astra Control Center 最多支援 5 、 000 個 LDAP 遠端群組。

.步驟
. 前往*帳戶*區域。
. 選取*使用者與群組*索引標籤。
. 在頁面最右側、選取*遠端群組*。
. 選取*「Add*」。
+
在此視窗中、您可以看到Astra Control從目錄擷取的LDAP群組一般名稱和辨別名稱清單。

. 或者、您也可以在*依一般名稱篩選*欄位中輸入群組的一般名稱、以搜尋LDAP群組。
. 從清單中選取一或多個群組。
. 指派角色給群組。
+

NOTE: 您選取的角色會指派給此群組中的所有使用者。如果您指派不同的角色給使用者和使用者群組、則權限越高的角色優先。

. 您也可以將一或多個命名空間限制指派給此群組、然後選取*限制角色限制*以強制執行限制。您可以選取*新增限制*來新增命名空間限制。
+

NOTE: 當使用者透過LDAP群組成員資格指派多個角色時、最具權限角色的限制是唯一會生效的限制。例如、如果具有本機檢視器角色的使用者加入三個繫結至「成員」角色的群組、則「成員」角色的限制總和會生效、而且會忽略「檢視器」角色的任何限制。

. 選取*「Add*」。


.結果
新群組會出現在遠端群組清單中。此群組中的遠端使用者不會出現在遠端使用者清單中、直到每個遠端使用者登入為止。在此清單中、您可以查看群組的詳細資料、也可以從*「動作」*功能表管理群組。
