---
sidebar: sidebar 
permalink: use/manage-connections.html 
keywords: manage package, packages, install 
summary: 您可以上傳並安裝套件至Astra Control Center。 
---
= 管理儲存庫連線
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


您可以將儲存庫連線至Astra Control、作為軟體套件安裝映像和成品的參考。當您匯入軟體套件時、Astra Control會參考映像儲存庫中的安裝映像、二進位檔及成品儲存庫中的其他成品。

.您需要的是 #8217 ；需要的是什麼
* Kubernetes叢集已安裝Astra Control Center
* 可存取的執行中Docker儲存庫
* 可存取的執行中成品儲存庫（例如Artifactory）




== 連接Docker映像儲存庫

您可以連接Docker映像儲存庫來保存套件安裝映像、例如Astra Data Store的安裝映像。安裝套件時、Astra Control會從映像儲存庫匯入套件映像檔。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*連線*索引標籤。
. 在「* Docker Image Repository *」（* Docker影像儲存庫*）區段中、選取右上角的功能表。
. 選擇*連接*。
. 新增儲存庫的URL和連接埠。
. 輸入儲存庫的認證資料。
. 選擇*連接*。


儲存庫已連線。在「* Docker Image Repository *」（* Docker映像儲存庫*）區段中、儲存庫應顯示連線狀態。



== 中斷Docker映像儲存庫的連線

如果不再需要、您可以移除與Docker映像儲存庫的連線。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*連線*索引標籤。
. 在「* Docker Image Repository *」（* Docker影像儲存庫*）區段中、選取右上角的功能表。
. 選擇*中斷連線*。
. 選取*是、中斷Docker映像儲存庫的連線*。


儲存庫已中斷連線。在「* Docker Image Repository *」（* Docker映像儲存庫*）區段中、儲存庫應顯示中斷連線狀態。



== 連接成品儲存庫

您可以將成品儲存庫連線至主機成品、例如軟體套件二進位檔。安裝套件時、Astra Control會從映像儲存庫匯入軟體套件的成品。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*連線*索引標籤。
. 在「*雜訊儲存庫*」區段中、選取右上角的功能表。
. 選擇*連接*。
. 新增儲存庫的URL和連接埠。
. 如果需要驗證、請啟用「*使用驗證*」核取方塊、然後輸入儲存庫的認證資料。
. 選擇*連接*。


儲存庫已連線。在「*雜訊儲存庫*」區段中、儲存庫應顯示連線狀態。



== 中斷成品儲存庫的連線

如果不再需要、您可以移除與成品儲存庫的連線。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*連線*索引標籤。
. 在「*雜訊儲存庫*」區段中、選取右上角的功能表。
. 選擇*中斷連線*。
. 選取*是、中斷產出工件儲存庫的連線*。


儲存庫已中斷連線。在「*雜訊儲存庫*」區段中、儲存庫應顯示連線狀態。

[discrete]
== 如需詳細資訊、請參閱

* link:manage-packages-acc.html["管理軟體套件"]

