---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: 將使用者新增至您的Astra Control Center系統、並移除不應再擁有系統存取權的使用者。 
---
= 管理使用者
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


您可以使用Astra Control UI來邀請、新增、移除及編輯Astra Control Center安裝的使用者。您可以使用Astra Control UI或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 管理使用者：

您也可以使用LDAP為選取的使用者執行驗證。



== 使用LDAP

LDAP是存取分散式目錄資訊的業界標準傳輸協定、也是企業驗證的熱門選擇。您可以將Astra Control Center連線至LDAP伺服器、為選取的Astra使用者執行驗證。在高層級上、組態包括將Astra與LDAP整合、以及定義與LDAP定義對應的Astra使用者和群組。請參閱 https://docs.netapp.com/us-en/astra-automation/workflows_infra/ldap_prepare.html["LDAP驗證"^] 以取得更多資訊。



== 邀請使用者

帳戶擁有者和管理員可以邀請新使用者前往Astra Control Center。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*使用者*索引標籤。
. 選擇*邀請使用者*。
. 輸入使用者名稱和電子郵件地址。
. 選取具有適當系統權限的使用者角色。
+
每個角色都提供下列權限：

+
** *檢視器*可以檢視資源。
** *成員*具有檢視者角色權限、可管理應用程式與叢集、取消管理應用程式、以及刪除快照與備份。
** 「*管理*」具有「成員角色」權限、可新增及移除擁有者以外的任何其他使用者。
** *擁有者*具有管理員角色權限、可新增及移除任何使用者帳戶。


. 若要新增限制給具有成員或檢視者角色的使用者、請啟用*限制角色限制*核取方塊。
+
如需新增限制的詳細資訊、請參閱 link:manage-roles.html["管理角色"]。

. 選擇*邀請使用者*。
+
使用者會收到一封電子郵件、通知他們已被邀請前往Astra Control Center。電子郵件包含暫時性密碼、首次登入時必須變更。





== 新增使用者

帳戶擁有者和系統管理員可以新增更多使用者至Astra Control Center安裝。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*使用者*索引標籤。
. 選取*新增使用者*。
. 輸入使用者的名稱、電子郵件地址和暫用密碼。
+
使用者必須在第一次登入時變更密碼。

. 選取具有適當系統權限的使用者角色。
+
每個角色都提供下列權限：

+
** *檢視器*可以檢視資源。
** *成員*具有檢視者角色權限、可管理應用程式與叢集、取消管理應用程式、以及刪除快照與備份。
** 「*管理*」具有「成員角色」權限、可新增及移除擁有者以外的任何其他使用者。
** *擁有者*具有管理員角色權限、可新增及移除任何使用者帳戶。


. 若要新增限制給具有成員或檢視者角色的使用者、請啟用*限制角色限制*核取方塊。
+
如需新增限制的詳細資訊、請參閱 link:manage-roles.html["管理角色"]。

. 選取*「Add*」。




== 管理密碼

您可以在Astra Control Center中管理使用者帳戶的密碼。



=== 變更您的密碼

您可以隨時變更使用者帳戶的密碼。

.步驟
. 選取畫面右上角的使用者圖示。
. 選擇*設定檔*。
. 從「*動作*」欄的「選項」功能表中選取「*變更密碼*」。
. 輸入符合密碼需求的密碼。
. 再次輸入密碼進行確認。
. 選擇*變更密碼*。




=== 重設其他使用者的密碼

如果您的帳戶具有「管理員」或「擁有者」角色權限、您可以重設其他使用者帳戶和您自己的密碼。當您重設密碼時、您會設定使用者登入時必須變更的暫用密碼。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取「*動作*」下拉式清單。
. 選擇*重設密碼*。
. 輸入符合密碼需求的暫用密碼。
. 再次輸入密碼進行確認。
+

NOTE: 下次使用者登入時、系統會提示使用者變更密碼。

. 選擇*重設密碼*。




== 變更使用者的角色

擁有擁有者角色的使用者可以變更所有使用者的角色、而擁有管理員角色的使用者則可以變更擁有管理員、成員或檢視者角色的使用者角色。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取「*動作*」下拉式清單。
. 選擇*編輯角色*。
. 選取新角色。
. 若要將限制套用至角色、請啟用*限制角色至限制*核取方塊、然後從清單中選取限制。
+
如果沒有限制、您可以新增限制。如需詳細資訊、請參閱 link:manage-roles.html["管理角色"]。

. 選擇* Confirm（確認）*。


Astra Control Center會根據您選取的新角色來更新使用者權限。



== 移除使用者

擁有擁有者或管理員角色的使用者可以隨時從帳戶中移除其他使用者。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 在「*使用者*」索引標籤中、選取您要移除之每個使用者列中的核取方塊。
. 從「*動作*」欄的「選項」功能表中、選取「*移除使用者*」。
. 出現提示時、請輸入「移除」一詞、然後選取「是、移除使用者*」、確認刪除。


Astra Control Center會將使用者從帳戶中移除。
