---
sidebar: sidebar 
permalink: use/manage-local-users-and-roles.html 
keywords: add users, edit users, remove users, delete users, manage roles 
summary: 管理Astra Control Center系統上的使用者和角色。 
---
= 管理本機使用者和角色
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
您可以使用Astra Control UI來新增、移除及編輯Astra Control Center安裝的使用者。您可以使用Astra Control UI或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 管理使用者：

您也可以使用LDAP為選取的使用者執行驗證。



== 使用LDAP

LDAP是存取分散式目錄資訊的業界標準傳輸協定、也是企業驗證的熱門選擇。您可以將Astra Control Center連線至LDAP伺服器、為選取的Astra Control使用者執行驗證。在高層級上、組態包括將Astra與LDAP整合、以及定義與LDAP定義對應的Astra Control使用者和群組。您可以使用Astra Control API或Web UI來設定LDAP驗證、以及LDAP使用者和群組。如需詳細資訊、請參閱下列文件：

* https://docs.netapp.com/us-en/astra-automation/workflows_infra/ldap_prepare.html["使用Astra Control API來管理遠端驗證和使用者"^]
* link:manage-remote-users-groups.html["使用Astra Control UI來管理遠端使用者和群組"]
* link:manage-remote-authentication.html["使用Astra Control UI來管理遠端驗證"]




== 新增使用者

帳戶擁有者和系統管理員可以新增更多使用者至Astra Control Center安裝。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*使用者*索引標籤。
. 選取*新增使用者*。
. 輸入使用者的名稱、電子郵件地址和暫用密碼。
+
使用者必須在第一次登入時變更密碼。

. 選取具有適當系統權限的使用者角色。
+
每個角色都提供下列權限：

+
** *檢視器*可以檢視資源。
** *成員*具有檢視者角色權限、可管理應用程式與叢集、取消管理應用程式、以及刪除快照與備份。
** 「*管理*」具有「成員角色」權限、可新增及移除擁有者以外的任何其他使用者。
** *擁有者*具有管理員角色權限、可新增及移除任何使用者帳戶。


. 若要新增限制給具有成員或檢視者角色的使用者、請啟用*限制角色限制*核取方塊。
+
如需新增限制的詳細資訊、請參閱 link:manage-local-users-and-roles.html["管理本機使用者和角色"]。

. 選取*「Add*」。




== 管理密碼

您可以在Astra Control Center中管理使用者帳戶的密碼。



=== 變更您的密碼

您可以隨時變更使用者帳戶的密碼。

.步驟
. 選取畫面右上角的使用者圖示。
. 選擇*設定檔*。
. 從「*動作*」欄的「選項」功能表中選取「*變更密碼*」。
. 輸入符合密碼需求的密碼。
. 再次輸入密碼進行確認。
. 選擇*變更密碼*。




=== 重設其他使用者的密碼

如果您的帳戶具有「管理員」或「擁有者」角色權限、您可以重設其他使用者帳戶和您自己的密碼。當您重設密碼時、您會設定使用者登入時必須變更的暫用密碼。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取「*動作*」下拉式清單。
. 選擇*重設密碼*。
. 輸入符合密碼需求的暫用密碼。
. 再次輸入密碼進行確認。
+

NOTE: 下次使用者登入時、系統會提示使用者變更密碼。

. 選擇*重設密碼*。




== 移除使用者

擁有擁有者或管理員角色的使用者可以隨時從帳戶中移除其他使用者。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 在「*使用者*」索引標籤中、選取您要移除之每個使用者列中的核取方塊。
. 從「*動作*」欄的「選項」功能表中、選取「*移除使用者*」。
. 出現提示時、請輸入「移除」一詞、然後選取「是、移除使用者*」、確認刪除。


.結果
Astra Control Center會將使用者從帳戶中移除。



== 管理角色

您可以新增命名空間限制、並將使用者角色限制在這些限制中、藉此管理角色。這可讓您控制組織內資源的存取。您可以使用Astra Control UI或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以管理角色。



=== 將命名空間限制新增至角色

管理員或擁有者使用者可以將命名空間限制新增至「成員」或「檢視者」角色。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*使用者*索引標籤。
. 在「*動作*」欄中、選取具有「成員」或「檢視者」角色的使用者功能表按鈕。
. 選擇*編輯角色*。
. 啟用「限制角色*」核取方塊。
+
此核取方塊僅適用於「成員」或「檢視者」角色。您可以從*角色*下拉式清單中選取不同的角色。

. 選取*新增限制*。
+
您可以依命名空間或命名空間標籤檢視可用限制清單。

. 在*限制類型*下拉式清單中、視命名空間的設定方式而定、選取* Kubernetes命名空間*或* Kubernetes命名空間標籤*。
. 從清單中選取一或多個命名空間或標籤、以構成限制、限制角色只能使用這些命名空間。
. 選擇* Confirm（確認）*。
+
「*編輯角色*」頁面會顯示您為此角色選擇的限制清單。

. 選擇* Confirm（確認）*。
+
在「*帳戶*」頁面上、您可以在「*角色*」欄中檢視任何成員或檢視者角色的限制條件。




NOTE: 如果您啟用角色的限制、並選取* Confirm（確認）*而不新增任何限制、則該角色會被視為具有完整限制（該角色無法存取指派給命名空間的任何資源）。



=== 從角色移除命名空間限制

管理員或擁有者使用者可以從角色移除命名空間限制。

.步驟
. 在*管理您的帳戶*導覽區域中、選取*帳戶*。
. 選取*使用者*索引標籤。
. 在「*動作*」欄中、選取具有作用中限制之「成員」或「檢視者」角色的使用者功能表按鈕。
. 選擇*編輯角色*。
+
「*編輯角色*」對話方塊會顯示角色的作用中限制。

. 選取您需要移除之限制右側的* X*。
. 選擇* Confirm（確認）*。




== 以取得更多資訊

* link:../concepts/user-roles-namespaces.html["使用者角色和命名空間"]

