---
sidebar: sidebar 
permalink: use/replicate_snapmirror.html 
keywords: replicate, replication, disaster, recovery 
summary: Astra可從快照或備份還原應用程式組態和持續儲存設備。持續儲存備份會從物件存放區傳輸、因此從現有備份還原將能最快完成。 
---
= 使用 SnapMirror 技術在儲存設備後端之間複寫應用程式
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
使用Astra Control、您可以利用NetApp SnapMirror技術的非同步複寫功能、利用低RPO（恢復點目標）和低RTO（恢復時間目標）、為應用程式建立營運不中斷。設定完成後、您的應用程式就能將資料和應用程式變更從一個儲存後端複寫到另一個儲存後端、在同一個叢集或不同叢集之間複寫。

如需備份 / 還原與複寫之間的比較、請參閱 link:../concepts/data-protection.html["資料保護概念"]。

您可以在不同的案例中複寫應用程式、例如下列僅限內部部署、混合式和多雲端的案例：

* 內部站台 A 到內部站台 A
* 內部部署站台A到內部部署站台B
* 內部部署至雲端、Cloud Volumes ONTAP 使用不整合技術
* 將Cloud Volumes ONTAP 雲端技術整合至內部部署
* 雲端搭配從功能到雲端（在同一個雲端供應商的不同地區或不同的雲端供應商之間）Cloud Volumes ONTAP


Astra Control可在內部部署叢集、內部部署到雲端（使用Cloud Volumes ONTAP 原地功能）或在雲端之間（Cloud Volumes ONTAP 從地到Cloud Volumes ONTAP 地）複寫應用程式。


NOTE: 您可以在相反方向同時複寫不同的應用程式。例如、應用程式A、B、C可以從資料中心1複寫到資料中心2、而應用程式X、Y、Z可以從資料中心2複寫到資料中心1。

使用Astra Control、您可以執行下列與複寫應用程式相關的工作：

* <<設定複寫關係>>
* <<將複寫的應用程式上線至目的地叢集（容錯移轉）>>
* <<重新同步複寫失敗的情況>>
* <<反轉應用程式複寫>>
* <<將應用程式容錯移轉至原始來源叢集>>
* <<刪除應用程式複寫關係>>




== 複寫先決條件

Astra Control 應用程式複寫需要先滿足下列先決條件、才能開始進行：

* * ONTAP 叢集 * ：
+
** * Astra Trident * ： Astra Trident 版本 22.10 或更新版本必須同時存在於使用 ONTAP 作為後端的來源叢集和目的地 Kubernetes 叢集上。
** * 授權 * ：使用資料保護套件的 ONTAP SnapMirror 非同步授權必須同時在來源和目的地 ONTAP 叢集上啟用。請參閱 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["SnapMirror授權概述ONTAP"^] 以取得更多資訊。


* * 對等 * ：
+
** * 叢集與 SVM* ：必須對 ONTAP 儲存設備的後端進行對等處理。請參閱 https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["叢集與SVM對等概觀"^] 以取得更多資訊。
+

IMPORTANT: 確保兩個 ONTAP 叢集之間複寫關係中使用的 SVM 名稱是唯一的。

** *Astra Trident 與 SVM* ：對等的遠端 SVM 必須可用於目的地叢集上的 Astra Trident 。


* * Astra 控制中心 * ：
+

TIP: link:../get-started/install_acc.html["部署 Astra Control Center"^] 在第三個故障網域或次要站台中進行無縫災難恢復。

+
** * 託管叢集 * ：下列叢集必須新增至 Astra Control 、並由 Astra Control 加以管理、最適合在不同的故障網域或站台：
+
*** 來源 Kubernetes 叢集
*** 目的地 Kubernetes 叢集
*** 相關的 ONTAP 叢集


** * 使用者帳戶 * ：當您將 ONTAP 儲存後端新增至 Astra 控制中心時、請套用具有「 admin 」角色的使用者認證。此角色具有存取方法 `http` 和 `ontapi` 同時在ONTAP 來源叢集和目的地叢集上啟用。請參閱 https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_cluster_user_accounts.html#users-list["管理ONTAP 使用者帳戶、請參閱本文檔"^] 以取得更多資訊。


* *Astra Trident / ONTAP 組態 * ： Astra 控制中心要求您至少設定一個儲存後端、以支援來源叢集和目的地叢集的複寫。如果來源叢集和目的地叢集相同、則目的地應用程式應使用不同於來源應用程式的儲存後端、以獲得最佳恢復能力。



IMPORTANT: Astra Control 複寫支援使用單一儲存類別的應用程式。當您將應用程式新增至命名空間時、請確定該應用程式與命名空間中的其他應用程式具有相同的儲存類別。將 PVC 新增至複寫的應用程式時、請確定新的 PVC 與命名空間中的其他 PVC 具有相同的儲存類別。



== 設定複寫關係

設定複寫關係涉及下列事項：

* 選擇 Astra Control 拍攝應用程式快照的頻率（包括應用程式的 Kubernetes 資源、以及每個應用程式磁碟區的磁碟區快照）
* 選擇複寫排程（包括Kubernetes資源及持續磁碟區資料）
* 設定拍攝快照的時間


.步驟
. 從Astra Control左側導覽中、選取* Applications*。
. 選擇 * 資料保護 * > * 複寫 * 標籤。
. 選取 * 設定複寫原則 * 。或者、從「應用程式保護」方塊中選取「動作」選項、然後選取「設定複寫原則*」。
. 輸入或選取下列資訊：
+
** * 目的地叢集 * ：輸入目的地叢集（可以與來源叢集相同）。
** * 目的地儲存類別 * ：選取或輸入在目的地 ONTAP 叢集上使用對等 SVM 的儲存類別。最佳實務做法是、目的地儲存類別應指向不同於來源儲存類別的儲存後端。
** * 複寫類型 * ： `Asynchronous` 目前是唯一可用的複寫類型。
** *目的地命名空間*：為目的地叢集輸入新的或現有的目的地命名空間。
** （可選）通過選擇* Add namespace*並從下拉列表中選擇命名空間來添加其他命名空間。
** * 複寫頻率 * ：設定您希望 Astra Control 多久拍攝一次快照並複寫到目的地。
** * 偏移 * ：設定您想要 Astra Control 拍攝快照的小時數頂端的分鐘數。您可能想要使用偏移、使其不與其他排程作業一致。
+

TIP: 偏移備份和複寫排程、以避免排程重疊。例如、在每小時的最長時間執行備份、並排程複寫以 5 分鐘偏移和 10 分鐘間隔開始。



. 選取*下一步*、檢閱摘要、然後選取*儲存*。
+

NOTE: 一開始、狀態會在第一個排程發生之前顯示「app-mirror」（應用程式鏡射）。

+
Astra Control 會建立用於複寫的應用程式快照。

. 若要查看應用程式快照狀態、請選取 * 應用程式 * > * 快照 * 索引標籤。
+
快照名稱使用的格式 `replication-schedule-<string>`。Astra Control 會保留上次用於複寫的快照。成功完成複寫後、任何較舊的複寫快照都會刪除。



.結果
這會建立複寫關係。

Astra Control在建立關係後完成下列行動：

* 在目的地上建立命名空間（如果不存在）
* 在目的地命名空間上建立一個與來源應用程式PVCS對應的PVc。
* 擷取應用程式一致的初始快照。
* 使用初始快照建立持續磁碟區的 SnapMirror 關係。


「 * 資料保護 * 」頁面會顯示複寫關係的狀態和狀態：
<Health status> | <Relationship life cycle state>

例如：正常|已建立

深入瞭解本主題結尾的複寫狀態和狀態。



== 將複寫的應用程式上線至目的地叢集（容錯移轉）

使用 Astra Control 、您可以將複寫的應用程式容錯移轉至目的地叢集。此程序會停止複寫關係、並在目的地叢集上使應用程式上線。此程序不會停止來源叢集上的應用程式（如果運作正常）。

.步驟
. 從Astra Control左側導覽中、選取* Applications*。
. 選擇 * 資料保護 * > * 複寫 * 標籤。
. 從「動作」功能表中、選取 * 容錯移轉 * 。
. 在「容錯移轉」頁面中、檢閱資訊並選取*容錯移轉*。


.結果
容錯移轉程序會執行下列動作：

* 目的地應用程式是根據最新的複寫快照來啟動。
* 來源叢集和應用程式（如果運作正常）不會停止、將會繼續執行。
* 複寫狀態會變更為「容錯移轉」、並在完成後變更為「容錯移轉」。
* 來源應用程式的保護原則會根據容錯移轉時來源應用程式上的排程、複製到目的地應用程式。
* 如果來源應用程式已啟用一或多個還原後執行掛勾、則會為目的地應用程式執行這些執行掛勾。
* Astra Control會在來源叢集和目的地叢集上顯示應用程式及其各自的健全狀況。




== 重新同步複寫失敗的情況

重新同步作業會重新建立複寫關係。您可以選擇關聯的來源、以保留來源或目的地叢集上的資料。此作業會重新建立SnapMirror關係、以便在選擇的方向開始磁碟區複寫。

此程序會在重新建立複寫之前、停止新目的地叢集上的應用程式。


NOTE: 在重新同步程序期間、生命週期狀態會顯示為「Establishing」。

.步驟
. 從Astra Control左側導覽中、選取* Applications*。
. 選擇 * 資料保護 * > * 複寫 * 標籤。
. 從「動作」功能表中、選取 * 重新同步 * 。
. 在「ResSync（重新同步）」頁面中、選取包含您要保留之資料的來源或目的地應用程式執行個體。
+

CAUTION: 請謹慎選擇重新同步來源、因為目的地上的資料將被覆寫。

. 選擇*重新同步*以繼續。
. 輸入「resSync」以確認。
. 選取*是、重新同步*以完成。


.結果
* 「複寫」頁面會顯示「建立」作為複寫狀態。
* Astra Control會在新的目的地叢集上停止應用程式。
* Astra Control會使用SnapMirror重新同步、在所選方向重新建立持續Volume複寫。
* 「複寫」頁面會顯示更新的關係。




== 反轉應用程式複寫

這是將應用程式移至目的地儲存後端、同時繼續複寫回原始來源儲存後端的計畫作業。Astra Control 會停止來源應用程式、並在容錯移轉至目的地應用程式之前、將資料複寫到目的地。

在這種情況下、您要交換來源和目的地。

.步驟
. 從Astra Control左側導覽中、選取* Applications*。
. 選擇 * 資料保護 * > * 複寫 * 標籤。
. 從「動作」功能表中、選取 * 「反向複寫」 * 。
. 在「Reverse Replication」（反轉複寫）頁面中、檢閱資訊、然後選取* Reverse Replication*繼續。


.結果
下列動作是因為反轉複寫而發生：

* 原始來源應用程式的 Kubernetes 資源會擷取快照。
* 刪除應用程式的Kubernetes資源（保留PVCS和PVs）、即可順利停止原始來源應用程式的Pod。
* 當 Pod 關機之後、應用程式的磁碟區快照就會被擷取和複寫。
* SnapMirror關係中斷、使目的地磁碟區準備好進行讀寫。
* 應用程式的 Kubernetes 資源會從關機前快照還原、並使用原始來源應用程式關機後複寫的 Volume 資料。
* 複寫會以相反方向重新建立。




== 將應用程式容錯移轉至原始來源叢集

使用 Astra Control 、您可以在容錯移轉作業之後、使用下列作業順序來達成「容錯回復」。在此工作流程中、 Astra Control 會先複寫（重新同步）任何應用程式變更回原始來源應用程式、然後再反轉複寫方向。

此程序從已完成容錯移轉至目的地的關係開始、並涉及下列步驟：

* 從容錯移轉狀態開始。
* 重新同步關係。
* 反轉複寫。


.步驟
. 從Astra Control左側導覽中、選取* Applications*。
. 選擇 * 資料保護 * > * 複寫 * 標籤。
. 從「動作」功能表中、選取 * 重新同步 * 。
. 針對容錯回復作業、請選擇容錯移轉應用程式做為重新同步作業的來源（保留任何在容錯移轉後寫入的資料）。
. 輸入「resSync」以確認。
. 選取*是、重新同步*以完成。
. 重新同步完成後、請在「Data Protection（資料保護）」>「Replication（複寫）」索引標籤的「Actions（動作）」功能表中、選取* Reverse replection*（反轉複寫）。
. 在「Reverse Replication」（反轉複寫）頁面中、檢閱資訊並選取* Reverse Replication*。


.結果
這將「重新同步」和「反轉關係」作業的結果結合在一起、以便在原始來源叢集上使應用程式上線、並將複寫恢復至原始目的地叢集。



== 刪除應用程式複寫關係

刪除關係會產生兩個獨立的應用程式、兩者之間沒有任何關係。

.步驟
. 從Astra Control左側導覽中、選取* Applications*。
. 選擇 * 資料保護 * > * 複寫 * 標籤。
. 從「應用程式保護」方塊或關係圖中、選取 * 刪除複寫關係 * 。


.結果
刪除複寫關係之後會發生下列動作：

* 如果建立關係、但應用程式尚未在目的地叢集上上線（容錯移轉）、Astra Control會保留初始化期間建立的PVCS、並在目的地叢集上留下「空白」的託管應用程式、並保留目的地應用程式、以保留可能建立的任何備份。
* 如果應用程式已在目的地叢集上線（容錯移轉）、Astra Control會保留PVCS和目的地應用程式。來源和目的地應用程式現在被視為獨立的應用程式。備份排程會保留在兩個應用程式上、但不會彼此關聯。 




== 複寫關係健全狀況狀態和關係生命週期狀態

Astra Control會顯示複寫關係的關係健全狀況、以及複寫關係的生命週期狀態。



=== 複寫關係健全狀況狀態

下列狀態表示複寫關係的健全狀況：

* * 正常 * ：關係正在建立或已建立、最近的快照已成功傳輸。
* *警告*：關係可能是容錯移轉或容錯移轉（因此不再保護來源應用程式）。
* *重大*
+
** 關係正在建立或容錯移轉、最後一次的協調嘗試失敗。
** 建立關係、最後一次嘗試協調新增的永久虛擬基礎虛擬基礎虛擬基礎虛擬基礎虛擬基礎虛擬基礎層面時、就會失敗。
** 這種關係已建立（因此已複寫成功的快照、並可能進行容錯移轉）、但最近的快照無法複寫或無法複寫。






=== 複寫生命週期狀態

下列狀態反映複寫生命週期的不同階段：

* *正在建立*：正在建立新的複寫關係。Astra Control會視需要建立命名空間、在目的地叢集的新磁碟區上建立持續磁碟區宣告（PVCS）、並建立SnapMirror關係。此狀態也表示複寫正在重新同步或反轉複寫。
* *已建立*：存在複寫關係。Astra Control 會定期檢查 PVC 是否可用、檢查複寫關係、定期建立應用程式快照、並在應用程式中識別任何新的來源 PVC 。如果是、Astra Control會建立資源以將其納入複寫中。
* * 容錯移轉 * ： Astra Control 會中斷 SnapMirror 關係、並從上次成功複寫的應用程式快照中還原應用程式的 Kubernetes 資源。
* * 故障轉移 * ： Astra Control 停止從來源叢集複寫、在目的地上使用最近（成功）複寫的應用程式快照、並還原 Kubernetes 資源。
* *重新同步*：Astra Control使用SnapMirror重新同步、將重新同步來源上的新資料重新同步至重新同步目的地。此作業可能會根據同步方向覆寫目的地上的部分資料。Astra Control會停止在目的地命名空間上執行的應用程式、並移除Kubernetes應用程式。在重新同步程序期間、狀態會顯示為「Establing（正在建立）」。
* *反轉*：是將應用程式移至目的地叢集、同時繼續複寫回原始來源叢集的計畫性作業。Astra Control會停止來源叢集上的應用程式、將資料複寫到目的地、然後再將應用程式容錯移轉到目的地叢集。在反向複寫期間、狀態會顯示為「Establing（正在建立）」。
* *刪除*：
+
** 如果複寫關係已建立但尚未容錯移轉、Astra Control會移除複寫期間建立的PVCS、並刪除目的地託管應用程式。
** 如果複寫已失敗、Astra Control會保留PVCS和目的地應用程式。



