---
sidebar: sidebar 
permalink: use/upgrade-acc.html 
keywords: astra upgrade, upgrade astra control center, how to upgrade astra control, update 
summary: 若要升級Astra Control Center、您必須依照所述步驟下載套裝組合並升級。 
---
= 升級Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
若要升級Astra Control Center、請從NetApp 支援網站 下列網址下載安裝套裝軟體、並完成這些指示。您可以使用此程序、在連線網際網路或無線環境中升級Astra Control Center。

.您需要的是 #8217 ；需要的是什麼
* 升級前、請參閱 link:../get-started/requirements.html#operational-environment-requirements["營運環境需求"^] 確保您的環境仍符合Astra Control Center部署的最低需求。您的環境應具備下列條件：
+
** 支援的Astra Trident版本若要判斷您正在執行的版本、請針對現有的Astra Control Center執行下列命令：
+
[listing]
----
../../trident-installer/tridentctl -n trident version
----
+
請參閱 https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html#determine-the-version-to-upgrade-to["Astra Trident文件"] 升級舊版。

+

WARNING: 您必須升級至Astra Trident 22.10 * PRIOS*、才能升級至Kubernetes 1.25。

** 支援的Kubernetes發佈版本若要判斷您正在執行的版本、請針對現有的Astra Control Center執行下列命令： `kubectl get nodes -o wide`
** 足夠的叢集資源來判斷叢集資源、請在現有的Astra Control Center叢集中執行下列命令： `kubectl describe node <node name>`
** 您可以用來推送和上傳Astra Control Center映像的登錄
** 預設儲存類別若要判斷您的預設儲存類別、請針對現有的Astra Control Center執行下列命令： `kubectl get storageclass`


* （僅限OpenShift）確保所有叢集操作員都處於健全狀態且可用。
+
[listing]
----
kubectl get clusteroperators
----
* 確保所有API服務都處於健全狀態且可用。
+
[listing]
----
kubectl get apiservices
----
* 在開始升級之前、請先登出Astra Control Center UI。


Astra Control Center升級程序會引導您完成下列高層級步驟：

*  the Astra Control Center bundle
*  the bundle
*  the images to your local registry
*  the updated Astra Control Center operator
*  Astra Control Center
*  system status



IMPORTANT: 請勿刪除Astra Control Center運算子（例如、 `kubectl delete -f astra_control_center_operator_deploy.yaml`）在Astra Control Center升級或操作期間、隨時避免刪除Pod。


TIP: 當排程、備份和快照未執行時、請在維護期間執行升級。



== 下載Astra Control Center套裝組合

. 請從下載Astra Control Center套裝組合 https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["NetApp 支援網站"^]。檔案名稱類似於下列項目： `astra-control-center-[version].tar.gz`。
. （選用）驗證套裝組合的簽名：
+
[listing]
----
openssl dgst -sha256 -verify AstraControlCenter-public.pub -signature astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----




== 打開產品組合的包裝

. 擷取影像：
+
[listing]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== 請確認您已安裝NetApp Astra kubectl外掛程式

NetApp Astra kubectl命令列外掛程式可在執行與部署及升級Astra Control Center相關的一般工作時節省時間。

. 使用下列命令來判斷是否已安裝外掛程式：
+
[listing]
----
kubectl astra
----


此命令應提供kubecll外掛說明。如果命令傳回錯誤、請使用這些命令來安裝外掛程式 link:../get-started/install_acc.html#install-the-netapp-astra-kubectl-plugin["說明"]。



== 將映像新增至本機登錄

. 為您的Container引擎完成適當的步驟順序：


[role="tabbed-block"]
====
.Docker
--
. 變更為 `acc` 從tar套件中抽取的目錄：
+
範例：



[listing]
----
cd ../acc
----
. 將Astra Control Center映像目錄中的套件映像推送到本機登錄。執行命令之前、請先進行下列替代：
+
** 以<BUNDLE_FILE> Astra Control套裝組合檔案的名稱取代 (`acc.manifest.yaml`）。
** 以<MY_FULL_REGISTRY_PATH> Docker儲存庫的URL取代支援；例如 https://exampledownloads.jfrog.io/docker-astra-control/v1/[]。
** 以<MY_REGISTRY_USER> 使用者名稱取代。
** 以<MY_REGISTRY_TOKEN> 登錄的授權權杖取代。
+
[source, console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----




--
.Podman
--
. 登入您的登錄：
+
[source, console]
----
podman login <MY_FULL_REGISTRY_PATH>
----
. 執行下列指令碼、依照註解中的說明進行<your _inforation>替換：
+
[source, console]
----
# You need to be at the root of the tarball.
# You should see these files to confirm correct location:
#   acc.manifest.yaml
#   acc/

# Replace <YOUR_REGISTRY> with your own registry (e.g registry.customer.com or registry.customer.com/testing, etc..)
export REGISTRY=<YOUR_REGISTRY>
export PACKAGENAME=acc
export PACKAGEVERSION=22.11.0-82
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')

  # Remove path and keep imageName.
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')

  # Tag with local image repo.
  podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}

  # Push to the local repo.
  podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


--
====


== 安裝更新的Astra Control Center操作員

. 變更目錄：
+
[listing]
----
cd manifests
----
. 編輯Astra Control Center營運者部署yaml（「Astra _control_center_operer_deploy」、以參照您的本機登錄和機密。
+
[listing]
----
vim astra_control_center_operator_deploy.yaml
----
+
.. 如果您使用需要驗證的登錄、請取代或編輯的預設行 `imagePullSecrets: []` 提供下列功能：
+
[listing]
----
imagePullSecrets:
- name: <astra-registry-cred_or_custom_name_of_secret>
----
.. 變更 `[your_registry_path]` 適用於 `kube-rbac-proxy` 映像到您在中推入映像的登錄路徑  the images to your local registry,上一步。
.. 變更 `[your_registry_path]` 適用於 `acc-operator` 映像到您在中推入映像的登錄路徑  the images to your local registry,上一步。
.. 將下列值新增至「env」區段：
+
[listing]
----
- name: ACCOP_HELM_UPGRADETIMEOUT
  value: 300m
----
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *- name: ACCOP_HELM_UPGRADETIMEOUT*
          *value: 300m*
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----


. 安裝更新的Astra Control Center操作員：
+
[listing]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
回應範例：

+
[listing]
----
namespace/netapp-acc-operator unchanged
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io configured
role.rbac.authorization.k8s.io/acc-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role configured
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding unchanged
configmap/acc-operator-manager-config unchanged
service/acc-operator-controller-manager-metrics-service unchanged
deployment.apps/acc-operator-controller-manager configured
----
. 確認Pod正在執行：
+
[listing]
----
kubectl get pods -n netapp-acc-operator
----




== 升級Astra Control Center

. 編輯Astra Control Center自訂資源（CR）：
+
[listing]
----
kubectl edit AstraControlCenter -n [netapp-acc or custom namespace]
----
. 變更Astra版本號碼 (`astraVersion` 內部 `Spec`）升級至您要升級的版本：
+
[listing, subs="+quotes"]
----
spec:
  accountName: "Example"
  *astraVersion: "[Version number]"*
----
. 確認您的映像登錄路徑符合您在中推送映像的登錄路徑  the images to your local registry,上一步。更新 `imageRegistry` 內部 `Spec` 如果登錄自上次安裝後有所變更。
+
[listing]
----
  imageRegistry:
    name: "[your_registry_path]"
----
. 將下列項目新增至 `CRDs` 的內部組態 `Spec`：
+
[listing]
----
crds:
  shouldUpgrade: true
----
. 在Astra Control Center CR的「Pec」內的「additionalValues」中新增下列行：
+
[listing]
----
additionalValues:
    nautilus:
      startupProbe:
        periodSeconds: 30
        failureThreshold: 600
----
+
儲存並結束檔案編輯器之後、將會套用變更並開始升級。

. （可選）驗證Pod是否終止並再次可用：
+
[listing]
----
watch kubectl get pods -n [netapp-acc or custom namespace]
----
. 等待Astra狀態條件顯示升級已完成且準備就緒 (`True`）：
+
[listing]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
回應：

+
[listing]
----
NAME    UUID                                      VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.11.0-24  10.111.111.111  True
----
+

NOTE: 若要在作業期間監控升級狀態、請執行下列命令： `kubectl get AstraControlCenter -o yaml -n [netapp-acc or custom namespace]`

+

NOTE: 若要檢查Astra控制中心的操作員記錄、請執行下列命令：
`kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f`





== 驗證系統狀態

. 登入Astra Control Center。
. 確認版本已升級。請參閱UI中的* Support*頁面。
. 確認您所有的託管叢集和應用程式仍存在且受到保護。

