---
sidebar: sidebar 
permalink: use/view-clusters.html 
keywords: view cluster, edit storage class, storage class, cluster storage, cluster overview 
summary: 將叢集新增至Astra Control Center之後、即可檢視叢集的詳細資料、例如其位置、工作節點、持續磁碟區和儲存類別。您也可以變更預設的儲存類別。 
---
= 檢視叢集健全狀況並管理儲存類別
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
新增要由Astra Control Center管理的叢集之後、您可以檢視叢集的詳細資料、例如其位置、工作節點、持續磁碟區和儲存類別。您也可以變更受管理叢集的預設儲存類別。



== 檢視叢集健全狀況和詳細資料

您可以檢視叢集的詳細資料、例如其位置、工作節點、持續磁碟區和儲存類別。

.步驟
. 在Astra Control Center UI中、選取* Clusters*。
. 在「*叢集*」頁面上、選取您要檢視其詳細資料的叢集。
+

NOTE: 如果叢集位於 `removed` 狀態但叢集和網路連線似乎正常（外部使用Kubernetes API存取叢集的嘗試成功）、您提供給Astra Control的Kubeconfig可能不再有效。這可能是因為叢集上的憑證輪替或過期。若要修正此問題、請使用更新Astra Control中與叢集相關的認證資料 https://docs.netapp.com/us-en/astra-automation["Astra Control API"]。

. 查看*概述*、*儲存設備*和*活動*索引標籤上的資訊、以尋找您要尋找的資訊。
+
** *總覽*：工作節點的詳細資料、包括其狀態。
** * Storage *：與運算相關的持續磁碟區、包括儲存類別和狀態。
** *活動*：顯示與叢集相關的活動。





NOTE: 您也可以從Astra控制中心*儀表板*開始檢視叢集資訊。在*叢集*索引標籤的*資源摘要*下、您可以選取受管理的叢集、然後前往*叢集*頁面。進入「*叢集*」頁面之後、請依照上述步驟操作。



== 變更預設儲存類別

您可以變更叢集的預設儲存類別。當Astra Control管理叢集時、它會追蹤叢集的預設儲存類別。


NOTE: 請勿使用kubectl命令變更儲存類別。請改用此程序。若使用KECBECVL、Astra Control將會回復變更。

.步驟
. 在Astra Control Center Web UI中、選取* Clusters*。
. 在「*叢集*」頁面上、選取您要變更的叢集。
. 選擇* Storage*（儲存設備）選項卡。
. 選擇*儲存類別*類別。
. 針對您要設為預設的儲存類別、選取「*動作*」功能表。
. 選擇*設為預設*。

