---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: astra faq, astra frequently asked questions, what is astra, astra control, kubernetes, persistent volumes 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= Astra Control Center的常見問題集
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 總覽

以下各節提供使用Astra Control Center時可能會遇到的其他問題解答。如需進一步的說明、請聯絡astra.feedback@netapp.com



== 存取Astra Control Center

*什麼是Astra Control URL？*

Astra Control Center使用本機驗證和每個環境的專屬URL。

對於URL、請在瀏覽器中輸入您在安裝Astra Control Center時、於Astra_control_center.yaml自訂資源（CR）檔案的SPEC.astraAddress欄位中所設定的完整網域名稱（FQDN）。電子郵件是您在Astra_control_center.yaml CR的spec.email*欄位中設定的值。



== 授權

* 我正在使用試用版授權。如何變更為完整授權？ *

您可以從 NetApp 取得 NetApp 授權檔案（ NLF ）、輕鬆變更為完整授權。

*步驟*

. 從左側導覽中、選取*帳戶*>*授權*。
. 在授權總覽中、於授權資訊右側、選取選項功能表。
. 選取 * 取代 * 。
. 瀏覽至您下載的授權檔案、然後選取*「Add*（新增*）」。


* 我正在使用試用版授權。我還能管理應用程式嗎？*

是的、您可以使用評估授權（包括預設安裝的內嵌評估授權）來測試管理應用程式功能。試用版授權與完整版授權之間的功能或功能並無差異；試用版授權的使用壽命更短。請參閱 link:../concepts/licensing.html["授權"^] 以取得更多資訊。



== 正在登錄Kubernetes叢集

*新增Astra Control之後、我需要將工作節點新增至Kubernetes叢集。我該怎麼辦？*

新的工作者節點可新增至現有的資源池。Astra Control會自動探索這些功能。如果在Astra Control中看不到新節點、請檢查新的工作節點是否執行支援的映像類型。您也可以使用「kubectl Get nodes」命令來驗證新工作節點的健全狀況。

*如何正確地取消管理叢集？*

. link:../use/unmanage.html["從Astra Control取消應用程式管理"]。
. link:../use/unmanage.html#stop-managing-compute["從Astra Control取消管理叢集"]。


*從Astra Control移除Kubernetes叢集之後、應用程式和資料會發生什麼變化？*

從Astra Control移除叢集不會對叢集的組態（應用程式和持續儲存）進行任何變更。在該叢集上執行的任何Astra Control快照或應用程式備份都無法還原。由Astra Control所建立的持續儲存備份仍在Astra Control之內、但無法還原。


WARNING: 透過任何其他方法刪除叢集之前、請務必先從Astra Control移除叢集。使用另一個工具刪除叢集時、如果叢集仍由Astra Control進行管理、可能會對Astra Control帳戶造成問題。

* 當我取消管理叢集時、 NetApp Astra Trident 是否會自動從叢集解除安裝？ * 當您從 Astra Control Center 取消管理叢集時、 Astra Trident 不會自動從叢集解除安裝。若要解除安裝Astra Trident、您需要 https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["請遵循Astra Trident文件中的下列步驟"^]。



== 管理應用程式

* Astra Control是否能部署應用程式？*

Astra Control不會部署應用程式。應用程式必須部署在Astra Control之外。

*停止從Astra Control管理應用程式之後、應用程式會發生什麼事？*

將刪除任何現有的備份或快照。應用程式與資料仍可繼續使用。資料管理作業無法用於未受管理的應用程式、或屬於它的任何備份或快照。

* Astra Control能否管理非NetApp儲存設備上的應用程式？*

不可以雖然Astra Control可以探索使用非NetApp儲存設備的應用程式、但它無法管理使用非NetApp儲存設備的應用程式。

* 我應該自行管理 Astra Control 嗎？ *

Astra Control Center 預設不會顯示為您可以管理的應用程式、但您可以使用其他 Astra Control Center 執行個體來備份和還原 Astra Control Center 執行個體。

不健康的 Pod 會影響應用程式管理嗎？ *

否、 Pod 的健全狀況不會影響應用程式管理。



== 資料管理作業

*我的應用程式使用數個PV。Astra Control是否會擷取這些PV的快照與備份？*

是的。Astra Control在應用程式上執行的快照作業包括繫結至應用程式PVCS的所有PV快照。

*我可以直接透過不同的介面或物件儲存設備來管理Astra Control所拍攝的快照嗎？*

不可以Astra Control所拍攝的快照與備份、只能透過Astra Control進行管理。
