---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: 若要在解決某些環境先決條件之後安裝Astra Control Center、您必須下載套裝軟組、並依照所述步驟安裝。 
---
= 使用標準程序安裝Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
若要安裝Astra Control Center、請從NetApp 支援網站 下列網址下載安裝套件、並執行下列步驟。您可以使用此程序、在連線網際網路或無線環境中安裝Astra Control Center。

.其他安裝程序
[%collapsible]
====
* *使用RedHat OpenShift操作員中樞*安裝：請使用此功能 link:../get-started/acc_operatorhub_install.html["替代程序"] 使用作業系統集線器在OpenShift上安裝Astra Control Center。
* *以Cloud Volumes ONTAP 支援功能的方式在公有雲上安裝*：使用 link:../get-started/install_acc-cvo.html["這些程序"] 若要在Amazon Web Services（AWS）、Google Cloud Platform（GCP）或Microsoft Azure中安裝Astra Control Center、並提供Cloud Volumes ONTAP 一套支援整合式儲存後端的功能。


====
.您需要的產品
* link:requirements.html["開始安裝之前、請先準備好環境以進行Astra Control Center部署"]。
* 如果您已設定或想要在環境中設定Pod安全性原則、請熟悉Pod安全性原則、以及這些原則如何影響Astra Control Center安裝。請參閱 link:../concepts/understand-pod-security.html["瞭解Pod安全性原則限制"]。
* 確保所有API服務均處於健全狀態且可供使用：
+
[source, console]
----
kubectl get apiservices
----
* 確保您打算使用的Astra FQDN可路由傳送至此叢集。這表示您在內部DNS伺服器中有DNS項目、或是使用已註冊的核心URL路由。
* 如果叢集中已存在認證管理程式、您需要執行某些作業 link:../get-started/cert-manager-prereqs.html["必要步驟"] 因此Astra Control Center不會嘗試安裝自己的認證管理程式。依預設、Astra Control Center會在安裝期間安裝自己的認證管理程式。


.關於這項工作
Astra Control Center安裝程序可協助您執行下列作業：

* 將Astra元件安裝至 `netapp-acc` （或自訂命名）命名空間。
* 建立預設的Astra Control擁有者管理帳戶。
* 建立管理使用者電子郵件地址和預設初始設定密碼。此使用者會被指派第一次登入UI時所需的擁有者角色。
* 確定所有Astra Control Center Pod都在執行中。
* 安裝Astra Control Center UI。



IMPORTANT: 請勿刪除Astra Control Center運算子（例如、 `kubectl delete -f astra_control_center_operator_deploy.yaml`）在Astra Control Center安裝或操作期間、隨時避免刪除Pod。

.步驟
若要安裝Astra Control Center、請執行下列步驟：

* <<下載並解壓縮Astra Control Center套裝組合>>
* <<安裝NetApp Astra kubecl外掛程式>>
* <<將映像新增至本機登錄>>
* <<設定具有驗證需求之登錄的命名空間和機密>>
* <<安裝Astra Control Center操作員>>
* <<設定Astra控制中心>>
* <<完整的Astra控制中心和操作員安裝>>
* <<驗證系統狀態>>
* <<設定入口以進行負載平衡>>
* <<登入Astra Control Center UI>>




== 下載並解壓縮Astra Control Center套裝組合

. 請從下載Astra Control Center套裝組合（「Astra控制中心-[版本].tar.gz」） https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["NetApp 支援網站"^]。
. 從下載Astra Control Center認證與金鑰的壓縮檔 https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["NetApp 支援網站"^]。
. （選用）驗證套裝組合的簽名：
+
[source, console]
----
openssl dgst -sha256 -verify AstraControlCenter-public.pub -signature astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----
. 擷取影像：
+
[source, console]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== 安裝NetApp Astra kubecl外掛程式

NetApp Astra kubectl命令列外掛程式可在執行與部署及升級Astra Control Center相關的一般工作時節省時間。

.您需要的產品
NetApp為不同的CPU架構和作業系統提供外掛程式二進位檔。執行此工作之前、您必須先瞭解您的CPU和作業系統。

.步驟
. 列出可用的NetApp Astra kubectl外掛程式二進位檔、並記下作業系統和CPU架構所需的檔案名稱：
+

NOTE: KECBECTl外掛程式庫是tar套件的一部分、會擷取到資料夾中 `kubectl-astra`。

+
[source, console]
----
ls kubectl-astra/
----
. 將正確的二進位檔移至目前路徑、並將其重新命名為 `kubectl-astra`：
+
[source, console]
----
cp kubectl-astra/<binary-name> /usr/local/bin/kubectl-astra
----




== 將映像新增至本機登錄

. 為您的Container引擎完成適當的步驟順序：


[role="tabbed-block"]
====
.Docker
--
. 切換到tar檔案的根目錄。您應該會看到這個檔案和目錄：
+
`acc.manifest.bundle.yaml`
`acc/`

. 將Astra Control Center映像目錄中的套件映像推送到本機登錄。執行之前、請先進行下列替換 `push-images` 命令：
+
** 以<BUNDLE_FILE> Astra Control套裝組合檔案的名稱取代 (`acc.manifest.bundle.yaml`）。
** 以<MY_FULL_REGISTRY_PATH> Docker儲存庫的URL取代支援；例如 https://exampledownloads.jfrog.io/docker-astra-control/v1/[]。
** 以<MY_REGISTRY_USER> 使用者名稱取代。
** 以<MY_REGISTRY_TOKEN> 登錄的授權權杖取代。
+
[source, console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----




--
.Podman
--
. 切換到tar檔案的根目錄。您應該會看到這個檔案和目錄：
+
`acc.manifest.bundle.yaml`
`acc/`

. 登入您的登錄：
+
[source, console]
----
podman login <MY_FULL_REGISTRY_PATH>
----
. 執行下列指令碼、依照註解中的說明進行<your _inforation>替換：
+
[source, console]
----
export REGISTRY=<YOUR_REGISTRY>
export PACKAGENAME=acc
export PACKAGEVERSION=22.11.0-82
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')

  # Remove path and keep imageName.
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')

  # Tag with local image repo.
  podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}

  # Push to the local repo.
  podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


--
====


== 設定具有驗證需求之登錄的命名空間和機密

. 匯出Astra Control Center主機叢集的KUBECCONFIG：
+
[source, console]
----
export KUBECONFIG=[file path]
----
+

NOTE: 完成安裝之前、請確定KUBECCONFIG指向您要安裝Astra Control Center的叢集。KUBECCONFIG只能包含一個內容。

. 如果您使用需要驗證的登錄、則需要執行下列動作：
+
.. 建立「NetApp-acc operator：
+
[source, console]
----
kubectl create ns netapp-acc-operator
----
+
回應：

+
[listing]
----
namespace/netapp-acc-operator created
----
.. 建立「NetApp-acc operator」命名空間的秘密。新增Docker資訊並執行下列命令：
+

NOTE: 預留位置 `your_registry_path` 應與您先前上傳的影像位置相符（例如、 `[Registry_URL]/netapp/astra/astracc/22.11.0-82`）。

+
[source, console]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
回應範例：

+
[listing]
----
secret/astra-registry-cred created
----
+

NOTE: 如果在產生機密之後刪除命名空間、請重新建立命名空間、然後重新產生命名空間的機密。

.. 建立 `netapp-acc` （或自訂命名）命名空間。
+
[source, console]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
回應範例：

+
[listing]
----
namespace/netapp-acc created
----
.. 為建立秘密 `netapp-acc` （或自訂命名）命名空間。新增Docker資訊並執行下列命令：
+
[source, console]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom namespace] --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
回應

+
[listing]
----
secret/astra-registry-cred created
----






== 安裝Astra Control Center操作員

. 變更目錄：
+
[source, console]
----
cd manifests
----
. 編輯Astra Control Center營運者部署Yaml（「Astra _control_center_operer_deploy」、以參照您的本機登錄和機密。
+
[source, console]
----
vim astra_control_center_operator_deploy.yaml
----
+

NOTE: 附註的Y反 洗錢範例遵循下列步驟。

+
.. 如果您使用需要驗證的登錄、請將預設行「imagePullSecrets：[]」改為：
+
[source, console]
----
imagePullSecrets:
- name: astra-registry-cred
----
.. 變更 `[your_registry_path]` 適用於 `kube-rbac-proxy` 映像到您在中推入映像的登錄路徑 <<將映像新增至本機登錄,上一步>>。
.. 變更 `[your_registry_path]` 適用於 `acc-operator-controller-manager` 映像到您在中推入映像的登錄路徑 <<將映像新增至本機登錄,上一步>>。
+
[source, subs="specialcharacters,quotes"]
----
*astra_control_center_operator_deploy.yaml*
----
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        - name: ACCOP_HELM_INSTALLTIMEOUT
          value: 5m
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----


. 安裝Astra Control Center操作員：
+
[source, console]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
回應範例：

+
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
. 確認Pod正在執行：
+
[source, console]
----
kubectl get pods -n netapp-acc-operator
----




== 設定Astra控制中心

. 編輯Astra Control Center自訂資源（CR）檔案 (`astra_control_center.yaml`）進行帳戶、AutoSupport 功能、登錄及其他必要的設定：
+

NOTE: 如需其他自訂項目、請熟悉所有項目 link:../get-started/acc_cluster_cr_options.html["CR選項及其潛在價值"^] 確保您的環境正確部署Astra Control Center。

+
[source, console]
----
vim astra_control_center.yaml
----
+

NOTE: 附註的Y反 洗錢範例遵循下列步驟。

+
.. *帳戶名稱*：變更 `accountName` 字串至您要與帳戶建立關聯的名稱。
.. * astraAddress*：變更 `astraAddress` 字串至您要在瀏覽器中使用的FQDN（建議）或IP位址、以存取Astra Control Center。這是您在完成時從負載平衡器配置的相同FQDN或IP位址 link:requirements.html["Astra Control Center需求"]。
+

NOTE: 請勿使用 `http://` 或 `https://` 地址中。複製此FQDN以供在中使用 <<登入Astra Control Center UI,後續步驟>>。

.. *《*》*《變更》AutoSupport `enrolled` for解決方案AutoSupport `false` 適用於沒有網際網路連線或無法保留的網站 `true` 適用於連線站台。
.. *電子郵件*：變更 `email` 字串至預設的初始系統管理員位址。複製此電子郵件地址以供在中使用 <<登入Astra Control Center UI,後續步驟>>。
.. *（選用）名字和姓氏*：新增名字 `firstName` 和姓氏 `lastName` 與帳戶相關聯的使用者。您可以在UI中立即或稍後執行此步驟。
.. *影像登錄*：變更 `[your_registry_path]` 移至您在中推送映像的登錄路徑 <<安裝Astra Control Center操作員,上一步>>。
+

IMPORTANT: 如果您使用的登錄不需要授權、則必須刪除 `secret` 行內 `imageRegistry` 否則安裝將會失敗。

.. *（選用）storageClass *：變更 `storageClass` 從「ONTAP-gold」到另一個Trident storageClass資源的價值（視安裝需求而定）。執行命令 `kubectl get sc` 以判斷您現有的已設定儲存類別。
.. *擷取類型*：使用下列其中一種入口類型：
+
*** *通用* (`ingressType: "Generic"`）（預設）
+
如果您使用另一個入口控制器、或偏好使用自己的入口控制器、請使用此選項。部署Astra Control Center之後、您需要設定 link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["入口控制器"] 使用URL公開Astra Control Center。

*** * AccTraefik* (`ingressType: "AccTraefik"`）
+
如果您不想設定入口控制器、請使用此選項。這會部署Astra控制中心 `traefik` 作為Kubernetes負載平衡器類型服務的閘道。

+
Astra Control Center使用「負載平衡器」類型的服務 (`svc/traefik` （在Astra Control Center命名空間中）、並要求指派可存取的外部IP位址。如果您的環境允許負載平衡器、但您尚未設定負載平衡器、則可以使用MetalLB或其他外部服務負載平衡器、將外部IP位址指派給服務。在內部DNS伺服器組態中、您應該將Astra Control Center所選的DNS名稱指向負載平衡的IP位址。

+

NOTE: 如需有關「負載平衡器」和入口服務類型的詳細資訊、請參閱 link:../get-started/requirements.html["需求"]。



.. * crds-*：如果使用外部認證管理程式、請變更 `externalCertManager` 至 `true`。預設值 `false` 讓Astra Control Center在安裝期間安裝自己的認證管理程式。




[source, subs="specialcharacters,quotes"]
----
*astra_control_center.yaml*
----
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  *accountName: "Example"*
  astraVersion: "ASTRA_VERSION"
  *astraAddress: "astra.example.com"*
  autoSupport:
    *enrolled: true*
  *email: "[admin@example.com]"*
  *firstName: "SRE"*
  *lastName: "Admin"*
  imageRegistry:
    *name: "[your_registry_path]"*
    *secret: "astra-registry-cred"*
  *storageClass: "ontap-gold"*
  volumeReclaimPolicy: "Retain"
  *ingressType: "Generic"*
  astraResourcesScaler: "Default"
  additionalValues: {}
  crds:
    externalTraefik: false
    *externalCertManager: false*
----


== 完整的Astra控制中心和操作員安裝

. 如果您尚未在上一步中執行此操作、請建立「NetApp-acc」（或自訂）命名空間：
+
[source, console]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
回應範例：

+
[listing]
----
namespace/netapp-acc created
----
. 在「NetApp-acc」（或您的自訂）命名空間中安裝Astra Control Center：
+
[source, console]
----
kubectl apply -f astra_control_center.yaml -n [netapp-acc or custom namespace]
----
+
回應範例：

+
[listing]
----
astracontrolcenter.astra.netapp.io/astra created
----




== 驗證系統狀態

您可以使用kubectl命令來驗證系統狀態。如果您偏好使用OpenShift、您可以使用相似的相關命令來進行驗證步驟。

.步驟
. 驗證是否已成功安裝所有系統元件。
+
[source, console]
----
kubectl get pods -n [netapp-acc or custom namespace]
----
+
每個Pod的狀態應為「執行中」。部署系統Pod可能需要幾分鐘的時間。

+
.回應範例
[%collapsible]
====
[listing, subs="+quotes"]
----
NAME                                       READY   STATUS    RESTARTS        AGE
acc-helm-repo-76d8d845c9-ggds2             1/1     Running   0               14m
activity-6cc67ff9f4-z48mr                  1/1     Running   2 (8m32s ago)   9m
api-token-authentication-7s67v             1/1     Running   0               8m56s
api-token-authentication-bplb4             1/1     Running   0               8m56s
api-token-authentication-p2c9z             1/1     Running   0               8m56s
asup-6cdfbc6795-md8vn                      1/1     Running   0               9m14s
authentication-9477567db-8hnc9             1/1     Running   0               7m4s
bucketservice-f4dbdfcd6-wqzkw              1/1     Running   0               8m48s
cert-manager-bb756c7c4-wm2cv               1/1     Running   0               14m
cert-manager-cainjector-c9bb86786-8wrf5    1/1     Running   0               14m
cert-manager-webhook-dd465db99-j2w4x       1/1     Running   0               14m
certificates-68dff9cdd6-kcvml              1/1     Running   2 (8m43s ago)   9m2s
certificates-68dff9cdd6-rsnsb              1/1     Running   0               9m2s
cloud-extension-69d48c956c-2s8dt           1/1     Running   3 (8m43s ago)   9m24s
cloud-insights-service-7c4f48b978-7gvlh    1/1     Running   3 (8m50s ago)   9m28s
composite-compute-7d9ff5f68-nxbhl          1/1     Running   0               8m51s
composite-volume-57b4756d64-nl66d          1/1     Running   0               9m13s
credentials-6dbc55f89f-qpzff               1/1     Running   0               11m
entitlement-67bfb6d7-gl6kp                 1/1     Running   4 (8m33s ago)   9m38s
features-856cc4dccc-mxbdb                  1/1     Running   0               9m20s
fluent-bit-ds-4rtsp                        1/1     Running   0               6m54s
fluent-bit-ds-9rqll                        1/1     Running   0               6m54s
fluent-bit-ds-w5mp7                        1/1     Running   0               6m54s
graphql-server-7c7cc49776-jz2kn            1/1     Running   0               2m29s
identity-87c59c975-9jpnf                   1/1     Running   0               9m6s
influxdb2-0                                1/1     Running   0               13m
keycloak-operator-84ff6d59d4-qcnmc         1/1     Running   0               7m1s
krakend-cbf6c7df9-mdtzv                    1/1     Running   0               2m30s
license-5b888b78bf-plj6j                   1/1     Running   0               9m32s
login-ui-846b4664dd-fz8hv                  1/1     Running   0               2m24s
loki-0                                     1/1     Running   0               13m
metrics-facade-779cc9774-n26rw             1/1     Running   0               9m18s
monitoring-operator-974db78f-pkspq         2/2     Running   0               6m58s
nats-0                                     1/1     Running   0               13m
nats-1                                     1/1     Running   0               13m
nats-2                                     1/1     Running   0               13m
nautilus-7bdc7ddc54-49tfn                  1/1     Running   0               7m50s
nautilus-7bdc7ddc54-cwc79                  1/1     Running   0               9m36s
openapi-5584ff9f46-gbrdj                   1/1     Running   0               9m17s
openapi-5584ff9f46-z9mzk                   1/1     Running   0               9m17s
packages-bfc58cc98-lpxq9                   1/1     Running   0               8m58s
polaris-consul-consul-server-0             1/1     Running   0               13m
polaris-consul-consul-server-1             1/1     Running   0               13m
polaris-consul-consul-server-2             1/1     Running   0               13m
polaris-keycloak-0                         1/1     Running   3 (6m15s ago)   6m56s
polaris-keycloak-1                         1/1     Running   0               4m22s
polaris-keycloak-2                         1/1     Running   0               3m41s
polaris-keycloak-db-0                      1/1     Running   0               6m56s
polaris-keycloak-db-1                      1/1     Running   0               4m23s
polaris-keycloak-db-2                      1/1     Running   0               3m36s
polaris-mongodb-0                          2/2     Running   0               13m
polaris-mongodb-1                          2/2     Running   0               13m
polaris-mongodb-2                          2/2     Running   0               12m
polaris-ui-5ccff47897-8rzgh                1/1     Running   0               2m33s
polaris-vault-0                            1/1     Running   0               13m
polaris-vault-1                            1/1     Running   0               13m
polaris-vault-2                            1/1     Running   0               13m
public-metrics-6cb7bfc49b-p54xm            1/1     Running   1 (8m29s ago)   9m31s
storage-backend-metrics-5c77994586-kjn48   1/1     Running   0               8m52s
storage-provider-769fdc858c-62w54          1/1     Running   0               8m54s
task-service-9ffc484c5-kx9f4               1/1     Running   3 (8m44s ago)   9m34s
telegraf-ds-bphb9                          1/1     Running   0               6m54s
telegraf-ds-rtsm2                          1/1     Running   0               6m54s
telegraf-ds-s9h5h                          1/1     Running   0               6m54s
telegraf-rs-lbpv7                          1/1     Running   0               6m54s
telemetry-service-57cfb998db-zjx78         1/1     Running   1 (8m40s ago)   9m26s
tenancy-5d5dfbcf9f-vmbxh                   1/1     Running   0               9m5s
traefik-7b87c4c474-jmgp2                   1/1     Running   0               2m24s
traefik-7b87c4c474-t9k8x                   1/1     Running   0               2m24s
trident-svc-c78f5b6bd-nwdsq                1/1     Running   0               9m22s
vault-controller-55bbc96668-c6425          1/1     Running   0               11m
vault-controller-55bbc96668-lq9n9          1/1     Running   0               11m
vault-controller-55bbc96668-rfkgg          1/1     Running   0               11m
----
====
. （選用）若要確保安裝完成、您可以使用下列命令來查看「acc operator」記錄。
+
[source, console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
+

NOTE: `accHost` 叢集登錄是最後一項作業、如果失敗、也不會導致部署失敗。如果記錄中指出叢集登錄失敗、您可以透過再次嘗試登錄 link:../get-started/setup_overview.html#add-cluster["在UI中新增叢集工作流程"] 或API。

. 當所有Pod都在執行時、請確認安裝成功 (`READY` 是 `True`）並取得您登入Astra Control Center時所使用的初始設定密碼：
+
[source, console]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
回應：

+
[listing]
----
NAME    UUID                                  VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.11.0-82  10.111.111.111  True
----
+

IMPORTANT: 複製UUID值。密碼為「ACC-」、後面接著UUID值（「ACC-[UUUID]」、或是在本範例中為「ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f」）。





== 設定入口以進行負載平衡

您可以設定Kubernetes入口控制器來管理外部服務存取。如果您使用的預設值、這些程序會提供入口控制器的設定範例 `ingressType: "Generic"` Astra Control Center自訂資源 (`astra_control_center.yaml`）。如果您指定、則不需要使用此程序 `ingressType: "AccTraefik"` Astra Control Center自訂資源 (`astra_control_center.yaml`）。

部署Astra Control Center之後、您需要設定入口控制器、以URL顯示Astra Control Center。

設定步驟視您使用的入口控制器類型而有所不同。Astra Control Center支援多種入站控制器類型。這些設定程序提供下列入口控制器類型的範例步驟：

* Istio入口
* Nginx入口控制器
* OpenShift入口控制器


.您需要的產品
* 必要的 https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/["入口控制器"] 應已部署。
* 。 https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class["入口等級"] 應已建立對應於入口控制器的。


.Istio入侵步驟
. 設定Istio入口。
+

NOTE: 此程序假設使用「預設」組態設定檔來部署Istio。

. 收集或建立Ingress閘道所需的憑證和私密金鑰檔案。
+
您可以使用CA簽署或自我簽署的憑證。一般名稱必須是Astra位址（FQDN）。

+
命令範例：

+
[source, console]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
----
. 建立秘密 `tls secret name` 類型 `kubernetes.io/tls` 中的TLS私密金鑰和憑證 `istio-system namespace` 如TLS機密所述。
+
命令範例：

+
[source, console]
----
kubectl create secret tls [tls secret name] --key="tls.key" --cert="tls.crt" -n istio-system
----
+

TIP: 機密名稱應與「isto-inple.yaml」檔案中提供的「pec.tls.secretName`」相符。

. 在中部署入口資源 `netapp-acc` （或自訂命名）命名空間、使用v1資源類型作為架構 (`istio-Ingress.yaml` 在本例中使用）：
+
[listing]
----
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC addess>
    secretName: [tls secret name]
  rules:
  - host: [ACC addess]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
----
. 套用變更：
+
[source, console]
----
kubectl apply -f istio-Ingress.yaml
----
. 檢查入侵狀態：
+
[source, console]
----
kubectl get ingress -n [netapp-acc or custom namespace]
----
+
回應：

+
[listing]
----
NAME    CLASS HOSTS             ADDRESS         PORTS   AGE
ingress istio astra.example.com 172.16.103.248  80, 443 1h
----
. <<設定Astra控制中心,完成Astra Control Center安裝>>。


.適用於Nginvin像 控制器的步驟
. 建立類型的秘密 `kubernetes.io/tls` 中的TLS私密金鑰和憑證 `netapp-acc` （或自訂命名）命名空間、如所述 https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets["TLS機密"]。
. 在中部署入口資源 `netapp-acc` （或自訂命名）命名空間、使用v1資源類型作為架構 (`nginx-Ingress.yaml` 在本例中使用）：
+
[source, yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp-acc-ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: [class name for nginx controller]
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: <ACC addess>
    http:
      paths:
        - path:
          backend:
            service:
              name: traefik
              port:
                number: 80
          pathType: ImplementationSpecific
----
. 套用變更：
+
[source, console]
----
kubectl apply -f nginx-Ingress.yaml
----



WARNING: NetApp建議將Ngin像 控制器安裝為部署、而非取消安裝。

.OpenShift入口控制器的步驟
. 取得您的憑證、取得可供OpenShift路由使用的金鑰、憑證和CA檔案。
. 建立OpenShift路由：
+
[source, console]
----
oc create route edge --service=traefik --port=web -n [netapp-acc or custom namespace] --insecure-policy=Redirect --hostname=<ACC address> --cert=cert.pem --key=key.pem
----




== 登入Astra Control Center UI

安裝Astra Control Center之後、您將變更預設管理員的密碼、並登入Astra Control Center UI儀表板。

.步驟
. 在瀏覽器中輸入FQDN (`https://<FQDN>`）您在中使用的 `astraAddress` 在中 `astra_control_center.yaml` 請於何時進行 <<設定Astra控制中心,您安裝了Astra Control Center>>。
. 收到提示時、請接受自我簽署的憑證。
+

NOTE: 您可以在登入後建立自訂憑證。

. 在Astra Control Center登入頁面、輸入您使用的值 `email` 在中 `astra_control_center.yaml` 請於何時進行 <<設定Astra控制中心,您安裝了Astra Control Center>>，然後輸入初始設定密碼 (`ACC-[UUID]`）。
+

NOTE: 如果您輸入錯誤密碼三次、系統將鎖定管理員帳戶15分鐘。

. 選擇*登入*。
. 出現提示時變更密碼。
+

NOTE: 如果這是您第一次登入、但您忘記密碼、而且尚未建立其他管理使用者帳戶、請聯絡 https://mysupport.netapp.com/site/["NetApp支援"] 以取得密碼恢復協助。

. （選用）移除現有的自我簽署TLS憑證、並以取代 link:../get-started/add-custom-tls-certificate.html["由憑證授權單位（CA）簽署的自訂TLS憑證"]。




== 疑難排解安裝

如果有任何服務處於「錯誤」狀態、您可以檢查記錄。尋找400到500範圍內的API回應代碼。這些都表示發生故障的地點。

.步驟
. 若要檢查Astra控制中心的操作員記錄、請輸入下列內容：
+
[source, console]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----




== 下一步

* （選用）視您的環境而定、請在安裝後完成 link:configure-after-install.html["組態步驟"]。
* 執行以完成部署 link:setup_overview.html["設定工作"]。

