---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters, tanzu, tkg, tkgi, grid, kubernetes, k8s 
summary: 驗證Kubernetes叢集、應用程式和網頁瀏覽器的支援、開始使用Astra Control Center。 
---
= Astra Control Center需求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
開始驗證作業環境、應用程式叢集、應用程式、授權和網頁瀏覽器的整備度。確保您的環境符合這些需求、以部署和操作 Astra Control Center 。



== 支援的主機叢集 Kubernetes 環境

Astra Control Center 已通過下列 Kubernetes 主機環境的驗證：


NOTE: 確保您選擇架設 Astra Control Center 的 Kubernetes 環境符合環境正式文件中所述的基本資源需求。

|===
| Kubernetes 在主機叢集上的發佈 | 支援的版本 


| Azure Stack HCI 上的 Azure Kubernetes 服務 | Azure Stack HCI 21H2 和 22H2 、含 1.24.x 和 1.5.x 


| Google Anthos | 1.15 至 1.16 （請參閱 <<Google Anthos 入口要求>>） 


| Kubernetes （上游） | 1.26 至 1.28 


| Rancher Kubernetes引擎（RKE） | RKE 1.3 搭配 Rancher Manager 2.6
RKE 1.4 搭配 Rancher Manager 2.7
RKE 2 （ v1.24.x ）搭配 Rancher 2.6
RKE 2 （ v1.26.x ）搭配 Rancher 2.7 


| Red Hat OpenShift Container Platform | 4.11 至 4.14 


| VMware Tanzu Kubernetes Grid整合版 | 1.16.x （請參閱 <<主機叢集資源需求>>） 
|===


== 主機叢集資源需求

除了環境的資源需求之外、Astra Control Center還需要下列資源：


NOTE: 這些需求假設Astra Control Center是營運環境中唯一執行的應用程式。如果環境正在執行其他應用程式、請相應調整這些最低需求。

* *CPU 擴充 * ：主機環境中所有節點的 CPU 都必須啟用 AVX 擴充功能。
* * 工作節點 * ：總計至少 3 個工作節點、每個節點有 4 個 CPU 核心和 12GB RAM
* * VMware Tanzu Kubernetes Grid 叢集需求 * ：在 VMware Tanzu Kubernetes Grid （ TKG ）或 Tanzu Kubernetes Grid 整合版（ TKGi ）叢集上代管 Astra Control Center 時、請謹記下列考量事項。
+
** 預設的VMware TKG和TKGi組態檔案權杖會在部署後10小時內過期。如果您使用Tanzu產品組合產品、則必須產生一個含有非過期權杖的Tanzu Kubernetes叢集組態檔、以避免Astra Control Center與託管應用程式叢集之間發生連線問題。如需相關指示、請造訪 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/nsx-application-platform/GUID-52A52C0B-9575-43B6-ADE2-E8640E22C29F.html["VMware NSxT-T資料中心產品文件。"^]
** 使用 `kubectl get nsxlbmonitors -A` 命令以查看您是否已設定服務監視器以接受入口流量。如果存在、則不應安裝MetalLB、因為現有的服務監視器將會覆寫任何新的負載平衡器組態。
** 停用要由Astra Control管理的任何應用程式叢集上的TKG或TKGi預設儲存類別強制。您可以編輯來執行此作業 `TanzuKubernetesCluster` 命名空間叢集上的資源。
** 在TKG或TKGi環境中部署Astra Control Center時、請注意Astra Trident的特定需求。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#other-known-configuration-options["Astra Trident文件"^]。






== 服務網狀網路需求

強烈建議在 Astra Control Center 主機叢集上安裝支援的 Istio 服務網格香草版本。請參閱 https://istio.io/latest/docs/releases/supported-releases/["支援版本"^] 適用於受支援版本的 Istio 。Istio 服務網格（例如 OpenShift Service Mesh ）的品牌版本未通過 Astra Control Center 驗證。

若要將 Astra Control Center 與主機叢集上安裝的 Istio 服務網格整合、您必須將整合作為 Astra Control Center 的一部分 link:../get-started/install_acc.html["安裝"] 不受此程序影響。


NOTE: 在主機叢集上安裝 Astra Control Service 而不設定服務網格、可能會對安全性造成嚴重影響。



== Astra Trident的需求

確保您符合下列特定環境需求的 Astra Trident 要求：

* * 與 Astra Control Center 搭配使用的最低版本 * ： Astra Trident 23.01 或更新版本已安裝及設定
* *Astra Trident 的 ONTAP 組態 * ：
+
** * 儲存類別 * ：在叢集上至少設定一個 Astra Trident 儲存類別。如果已設定預設儲存類別、請確定它是唯一具有預設指定的儲存類別。
** * 儲存驅動程式與工作節點 * ：請務必使用適當的儲存驅動程式來設定叢集中的工作節點、以便 Pod 與後端儲存設備互動。Astra Control Center支援ONTAP Astra Trident提供的下列支援資訊驅動程式：
+
*** `ontap-nas`
*** `ontap-san`
*** `ontap-san-economy` （此儲存類別類型無法使用應用程式複寫）
*** `ontap-nas-economy` （此儲存類別類型無法使用快照和複寫原則）








== Astra Control 資源配置程式

若要使用 Astra Control Provisioner 進階儲存功能、您必須安裝 Astra Trident 23.10 或更新版本並啟用 link:../use/enable-acp.html["Astra Control Provisioner 功能"]。



== 儲存設備後端

確保您擁有支援的後端、且具有足夠的容量。

* * 所需的儲存後端容量 * ：可用容量至少 500 GB
* * 支援的後端 * ： Astra Control Center 支援下列儲存後端：
+
** NetApp ONTAP 9.9.1 或更新版本的 AFF 、 FAS 和 ASA 系統
** NetApp ONTAP Select 9.9.1 或更新版本
** NetApp Cloud Volumes ONTAP 9.9.1 或更新版本
** Longhorn 1.5.0 或更新版本
+
*** 需要手動建立 Volume SnapshotClass 物件。請參閱 https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/#create-a-csi-volumesnapshot-associated-with-longhorn-snapshot["Longhorn 文件"^] 以取得相關指示。


** NetApp MetroCluster
+
*** 託管 Kubernetes 叢集必須採用彈性組態。


** 支援的雲端供應商可提供儲存設備後端






=== 不需要授權ONTAP

若要使用Astra Control Center、請視ONTAP 您需要完成的工作而定、確認您擁有下列各項的版次授權：

* FlexClone
* SnapMirror：選用。僅使用SnapMirror技術複寫至遠端系統時才需要。請參閱 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["SnapMirror授權資訊"^]。
* S3授權：選用。僅適用於SS3鏟斗ONTAP


若要檢查ONTAP 您的不實系統是否有必要的授權、請參閱 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["管理ONTAP 不需購買的授權"^]。



=== NetApp MetroCluster

當您使用 NetApp MetroCluster 作為儲存後端時、必須執行下列動作：

* 在您使用的 Astra Trident 驅動程式中、將 SVM 管理 LIF 指定為後端選項
* 請確定您擁有適當的 ONTAP 授權


若要設定 MetroCluster LIF 、請參閱 Astra Trident 文件、以取得每個驅動程式的詳細資訊：

* https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["SAN"^]
* https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["NAS"^]




== 映像登錄

您必須擁有現有的私有 Docker 映像登錄、才能將 Astra Control Center 建置映像推送至該登錄。您需要提供映像登錄的URL、以便上傳映像。



== Astra Control Center 授權

Astra Control Center 需要 Astra Control Center 授權。安裝 Astra Control Center 時、已啟動內嵌式 90 天試用版授權、可用於 4 、 800 個 CPU 單元。如果您需要更多容量或不同的評估條款、或想要升級至完整授權、您可以向 NetApp 取得不同的評估授權或完整授權。您需要授權來保護應用程式和資料。

您可以報名免費試用 Astra Control Center 。您可以註冊註冊 link:https://bluexp.netapp.com/astra-register["請按這裡"^]。

若要設定授權、請參閱 link:setup_overview.html["使用90天試用版授權"^]。

若要深入瞭解授權的運作方式、請參閱 link:../concepts/licensing.html["授權"^]。



== 網路需求

設定您的營運環境、確保 Astra Control Center 能夠正常通訊。需要下列網路組態：

* * FQDN 位址 * ：您必須擁有 Astra Control Center 的 FQDN 位址。
* * 存取網際網路 * ：您應該判斷是否有外部存取網際網路的權限。如果您沒有、部分功能可能會受到限制、例如從NetApp Cloud Insights 接收監控和數據資料、或是將支援組合傳送至 https://mysupport.netapp.com/site/["NetApp 支援網站"^]。
* * 連接埠存取 * ：裝載 Astra Control Center 的作業環境使用下列 TCP 連接埠進行通訊。您應確保這些連接埠可透過任何防火牆、並設定防火牆、以允許來自Astra網路的任何HTTPS輸出流量。有些連接埠需要在裝載Astra Control Center的環境與每個託管叢集之間進行連線（視情況而定）。



NOTE: 您可以在雙堆疊Kubernetes叢集中部署Astra Control Center、Astra Control Center則可管理已設定為雙堆疊作業的應用程式和儲存後端。如需雙堆疊叢集需求的詳細資訊、請參閱 https://kubernetes.io/docs/concepts/services-networking/dual-stack/["Kubernetes文件"^]。

|===
| 來源 | 目的地 | 連接埠 | 傳輸協定 | 目的 


| 用戶端PC | Astra控制中心 | 443.. | HTTPS | UI / API 存取 - 確保 Astra Control Center 和用於存取 Astra Control Center 的系統之間雙向開啟此連接埠 


| 度量使用者 | Astra Control Center工作節點 | 9090 | HTTPS | 度量資料通訊：確保每個託管叢集都能存取裝載Astra Control Center的叢集上的此連接埠（需要雙向通訊） 


| Astra控制中心 | 託管Cloud Insights 版的服務  | 443.. | HTTPS | 通訊Cloud Insights 


| Astra控制中心 | Amazon S3儲存貯體供應商 | 443.. | HTTPS | Amazon S3儲存通訊 


| Astra控制中心 | NetApp AutoSupport  | 443.. | HTTPS | NetApp AutoSupport 通訊 


| Astra控制中心 | 託管 Kubernetes 叢集 | 443/643.
* 注意 * ：受管理叢集使用的連接埠可能會因叢集而異。請參閱叢集軟體廠商提供的文件。 | HTTPS | 與託管叢集通訊：確保此連接埠在託管 Astra Control Center 的叢集和每個託管叢集之間都是開放的 
|===


== 內部部署Kubernetes叢集的入口

您可以選擇網路入侵Astra控制中心的用途類型。依預設、Astra Control Center會將Astra Control Center閘道（服務/網路）部署為整個叢集的資源。Astra Control Center也支援使用服務負載平衡器（如果環境允許）。如果您想要使用服務負載平衡器、但尚未設定一個、則可以使用MetalLB負載平衡器自動將外部IP位址指派給服務。在內部DNS伺服器組態中、您應該將Astra Control Center所選的DNS名稱指向負載平衡的IP位址。


NOTE: 負載平衡器應使用與Astra Control Center工作節點IP位址位於同一子網路中的IP位址。

如需詳細資訊、請參閱 link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["設定入口以進行負載平衡"^]。



=== Google Anthos 入口要求

在 Google Anthos 叢集上代管 Astra Control Center 時、請注意 Google Antos 預設包含 MetalLB 負載平衡器和 Istio 入口服務、讓您在安裝期間只需使用 Astra Control Center 的一般入口功能即可。請參閱 link:install_acc.html#configure-astra-control-center["設定Astra控制中心"^] 以取得詳細資料。



== 支援的網頁瀏覽器

Astra Control Center支援最新版本的Firefox、Safari和Chrome、最低解析度為1280 x 720。



== 應用程式叢集的其他需求

如果您打算使用這些Astra Control Center功能、請謹記以下要求：

* *應用程式叢集需求*： link:../get-started/setup_overview.html#prepare-your-environment-for-cluster-management-using-astra-control["叢集管理需求"^]
+
** *受管理的應用程式需求*： link:../use/manage-apps.html#application-management-requirements["應用程式管理需求"^]
** *應用程式複寫的其他需求*： link:../use/replicate_snapmirror.html#replication-prerequisites["複寫先決條件"^]






== 下一步

檢視 link:quick-start.html["快速入門"^] 總覽：
