---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters, tanzu, tkg, tkgi, grid, kubernetes, k8s 
summary: 驗證Kubernetes叢集、應用程式和網頁瀏覽器的支援、開始使用Astra Control Center。 
---
= Astra Control Center需求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
開始驗證作業環境、應用程式叢集、應用程式、授權和網頁瀏覽器的整備度。

* <<營運環境需求>>
* <<支援的儲存後端>>
* <<存取網際網路>>
* <<授權>>
* <<內部部署Kubernetes叢集的入口>>
* <<網路需求>>
* <<支援的網頁瀏覽器>>
* <<應用程式叢集的其他需求>>
* <<Google Anthos叢集需求>>
* <<VMware Tanzu Kubernetes Grid叢集需求>>




== 營運環境需求

Astra Control Center已在下列類型的作業環境中通過驗證：

* Cisco IKS搭配Kubernetes 1.22
* Google Anthos 1.11或1.12（請參閱 <<Google Anthos叢集需求>>）
* Rancher Kubernetes Engine（RKE）：
+
** RKE 1.3.12搭配Rancher 2.6.5和2.6.6
** RKE 1.3.13搭配Rancher 2.6.8
** RKE 2（v1.23.6+ rke2r1）搭配Rancher 2.6.5和2.6.6
** RKE 2（v1.24.x）搭配Rancher 2.6.8


* Red Hat OpenShift Container Platform 4.8至4.11
* 上游Kubernetes 1.23至1.25（Kubernetes 1.25需要Astra Trident 22.10或更新版本）
* VMware Tanzu Kubernetes Grid：（請參閱 <<VMware Tanzu Kubernetes Grid叢集需求>>）
+
** VMware Tanzu Kubernetes Grid 1.5
** VMware Tanzu Kubernetes Grid整合版1.13和1.14




確保您選擇裝載Astra Control Center的作業環境符合環境正式文件中所述的基本資源需求。除了環境的資源需求之外、Astra Control Center還需要下列資源：

|===
| 元件 | 需求 


| CPU擴充 | 託管環境中所有節點的CPU都必須啟用AVX擴充功能。 


| 儲存後端容量 | 至少可提供500GB容量 


| 工作節點  a| 
總共至少3個工作節點、每個節點有4個CPU核心和12GB RAM



| FQDN位址 | Astra Control Center的FQDN位址 


| Astra Trident  a| 
Astra Trident 22.01或更新版本已安裝並設定Astra Trident 22.07或更新版本、以供SnapMirror型應用程式複寫Astra Trident 22.10或更新版本安裝於Kubernetes 1.25叢集（您必須在升級至Kubernetes之前升級至Astra Trident 22.10）

|===

NOTE: 這些需求假設Astra Control Center是營運環境中唯一執行的應用程式。如果環境正在執行其他應用程式、請相應調整這些最低需求。

* *映像登錄*：您必須擁有現有的私有Docker映像檔登錄、才能將Astra Control Center建置映像推入其中。您需要提供映像登錄的URL、以便上傳映像。
* * Astra Trident / ONTAP S161*：
+
** Astra Control Center需要建立儲存類別、並將其設為預設儲存類別。
** 確保叢集中的工作節點已設定適當的儲存驅動程式、以便Pod與後端儲存設備互動。Astra Control Center支援ONTAP Astra Trident提供的下列支援資訊驅動程式：
+
*** ONTAP-NAS
*** ONTAP-NAS-flexgroup
*** ONTAP-SAN
*** ONTAP-san經濟型（不支援應用程式複寫）








== 支援的儲存後端

Astra Control Center支援下列儲存後端。

* NetApp ONTAP S9.5或更新AFF 版本的功能性和FAS 功能性系統
* 適用於ONTAP SnapMirror應用程式複寫的NetApp SnapMirror 9.8或更新AFF 版本的功能性和FAS 功能性系統
* NetApp Cloud Volumes ONTAP


若要使用Astra Control Center、請視ONTAP 您需要完成的工作而定、確認您擁有下列各項的版次授權：

* FlexClone
* SnapMirror：選用。僅使用SnapMirror技術複寫至遠端系統時才需要。請參閱 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["SnapMirror授權資訊"^]。
* S3授權：選用。僅適用於SS3鏟斗ONTAP


若要檢查ONTAP 您的不實系統是否有必要的授權、請參閱 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["管理ONTAP 不需購買的授權"^]。



== 存取網際網路

您應該判斷是否有外部網際網路存取權。如果您沒有、部分功能可能會受到限制、例如從NetApp Cloud Insights 接收監控和數據資料、或是將支援組合傳送至 https://mysupport.netapp.com/site/["NetApp 支援網站"^]。



== 授權

Astra Control Center需要Astra Control Center授權才能提供完整功能。向NetApp取得評估授權或完整授權。您需要授權來保護應用程式和資料。請參閱 link:../concepts/intro.html["Astra Control Center功能"] 以取得詳細資料。

您可以使用Astra Control Center試用試用試用版授權、從下載授權之日起90天內即可使用Astra Control Center。您可以註冊以免費試用 link:https://cloud.netapp.com/astra-register["請按這裡"^]。

若要設定授權、請參閱 link:setup_overview.html["使用90天試用版授權"^]。

若要深入瞭解授權的運作方式、請參閱 link:../concepts/licensing.html["授權"^]。

如需ONTAP 有關支援不支援的詳細資訊、請參閱 link:../get-started/requirements.html["支援的儲存後端"]。



== 內部部署Kubernetes叢集的入口

您可以選擇網路入侵Astra控制中心的用途類型。依預設、Astra Control Center會將Astra Control Center閘道（服務/網路）部署為整個叢集的資源。Astra Control Center也支援使用服務負載平衡器（如果環境允許）。如果您想要使用服務負載平衡器、但尚未設定一個、則可以使用MetalLB負載平衡器自動將外部IP位址指派給服務。在內部DNS伺服器組態中、您應該將Astra Control Center所選的DNS名稱指向負載平衡的IP位址。


NOTE: 負載平衡器應使用與Astra Control Center工作節點IP位址位於同一子網路中的IP位址。


NOTE: 如果您要在Tanzu Kubernetes Grid叢集上裝載Astra Control Center、請使用「kubecl Get nslb監 控器-A」命令、查看您是否已設定服務監控器來接受入口流量。如果存在、則不應安裝MetalLB、因為現有的服務監視器將會覆寫任何新的負載平衡器組態。

如需詳細資訊、請參閱 link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["設定入口以進行負載平衡"^]。



== 網路需求

裝載Astra Control Center的作業環境會使用下列TCP連接埠進行通訊。您應確保這些連接埠可透過任何防火牆、並設定防火牆、以允許來自Astra網路的任何HTTPS輸出流量。有些連接埠需要在裝載Astra Control Center的環境與每個託管叢集之間進行連線（視情況而定）。


NOTE: 您可以在雙堆疊Kubernetes叢集中部署Astra Control Center、Astra Control Center則可管理已設定為雙堆疊作業的應用程式和儲存後端。如需雙堆疊叢集需求的詳細資訊、請參閱 https://kubernetes.io/docs/concepts/services-networking/dual-stack/["Kubernetes文件"^]。

|===
| 來源 | 目的地 | 連接埠 | 傳輸協定 | 目的 


| 用戶端PC | Astra控制中心 | 443.. | HTTPS | UI / API存取：確保此連接埠在裝載Astra Control Center的叢集與每個受管理叢集之間都開啟 


| 度量使用者 | Astra Control Center工作節點 | 9090 | HTTPS | 度量資料通訊：確保每個託管叢集都能存取裝載Astra Control Center的叢集上的此連接埠（需要雙向通訊） 


| Astra控制中心 | 託管Cloud Insights 版的服務 (https://www.netapp.com/cloud-services/cloud-insights/)[] | 443.. | HTTPS | 通訊Cloud Insights 


| Astra控制中心 | Amazon S3儲存貯體供應商 | 443.. | HTTPS | Amazon S3儲存通訊 


| Astra控制中心 | NetApp AutoSupport (https://support.netapp.com)[] | 443.. | HTTPS | NetApp AutoSupport 通訊 
|===


== 支援的網頁瀏覽器

Astra Control Center支援最新版本的Firefox、Safari和Chrome、最低解析度為1280 x 720。



== 應用程式叢集的其他需求

如果您打算使用這些Astra Control Center功能、請謹記以下要求：

* *應用程式叢集需求*： link:../get-started/setup_overview.html#prepare-your-environment-for-cluster-management-using-astra-control["叢集管理需求"^]
+
** *受管理的應用程式需求*： link:../use/manage-apps.html#application-management-requirements["應用程式管理需求"^]
** *應用程式複寫的其他需求*： link:../use/replicate_snapmirror.html#replication-prerequisites["複寫先決條件"^]






== Google Anthos叢集需求

在Google Anthos叢集上裝載Astra Control Center時、請注意、Google Anthos預設包含MetalLB負載平衡器和Istio入口閘道服務、讓您在安裝期間只需使用Astra Control Center的一般入口功能即可。請參閱 link:install_acc.html#configure-astra-control-center["設定Astra控制中心"^] 以取得詳細資料。



== VMware Tanzu Kubernetes Grid叢集需求

在VMware Tanzu Kubernetes Grid（TKG）或Tanzu Kubernetes Grid整合版（TKGi）叢集上裝載Astra Control Center時、請謹記下列考量事項。

* 停用要由Astra Control管理的任何應用程式叢集上的TKG或TKGi預設儲存類別強制。您可以編輯命名空間叢集上的「TanzuKubernetesCluster」資源來執行此作業。
* 在TKG或TKGi環境中部署Astra Control Center時、請注意Astra Trident的特定需求。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#other-known-configuration-options["Astra Trident文件"^]。



NOTE: 預設的VMware TKG和TKGi組態檔案權杖會在部署後10小時內過期。如果您使用Tanzu產品組合產品、則必須產生一個含有非過期權杖的Tanzu Kubernetes叢集組態檔、以避免Astra Control Center與託管應用程式叢集之間發生連線問題。如需相關指示、請造訪 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/nsx-application-platform/GUID-52A52C0B-9575-43B6-ADE2-E8640E22C29F.html["VMware NSxT-T資料中心產品文件。"^]



== 下一步

檢視 link:quick-start.html["快速入門"^] 總覽：
