---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 已知問題可識別可能導致您無法成功使用本產品版本的問題。 
---
= 已知問題
:hardbreaks:
:allow-uri-read: 
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知問題可識別可能導致您無法成功使用本產品版本的問題。

下列已知問題會影響目前的版本：

.應用程式
* <<還原應用程式會導致PV大小大於原始PV>>
* <<使用特定版本的PostgreSQL時、應用程式複製失敗>>
* <<使用服務帳戶層級OCP安全內容限制（SCC）時、應用程式複製失敗>>
* <<應用程式複製在以設定的儲存類別部署應用程式之後失敗>>
* <<如果在管理叢集之後新增volumesnapshotClass、則應用程式備份和快照將會失敗>>


.叢集
* <<使用Astra Control Center管理叢集失敗、因為預設的Kbeconfig檔案包含多個內容>>


.其他問題
* <<透過Cloud Insights Proxy連線時、託管叢集不會出現在NetApp的整個過程中>>
* <<當Astra Trident離線時、應用程式資料管理作業會因內部服務錯誤（500）而失敗>>




== 還原應用程式會導致PV大小大於原始PV

如果您在建立備份之後調整持續磁碟區的大小、然後從該備份還原、則持續磁碟區大小將會與PV的新大小相符、而非使用備份的大小。



== 使用特定版本的PostgreSQL時、應用程式複製失敗

同一個叢集內的應用程式複製作業、會持續失敗、並顯示Bitnami PostgreSQL 11.5.0圖表。若要成功複製、請使用舊版或更新版本的圖表。



== 使用服務帳戶層級OCP安全內容限制（SCC）時、應用程式複製失敗

如果在OpenShift Container Platform叢集的命名空間中、於服務帳戶層級設定原始的安全性內容限制、則應用程式複製可能會失敗。當應用程式複製失敗時、它會出現在Astra Control Center的「託管應用程式」區域、狀態為「移除」。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center["知識庫文章"^] 以取得更多資訊。



== 如果在管理叢集之後新增volumesnapshotClass、則應用程式備份和快照將會失敗

在此情況下、備份和快照會失敗、並顯示「UI 500錯誤」。因應措施是重新整理應用程式清單。



== 應用程式複製在以設定的儲存類別部署應用程式之後失敗

在以明確設定的儲存類別（例如「helm install ...-set globe.storageClass = NetApp-CVs-perf-Extreme」）部署應用程式之後、後續嘗試複製應用程式時、必須讓目標叢集擁有原本指定的儲存類別。將具有明確設定儲存類別的應用程式複製到沒有相同儲存類別的叢集、將會失敗。在此案例中沒有任何恢復步驟。



== 使用Astra Control Center管理叢集失敗、因為預設的Kbeconfig檔案包含多個內容

您無法在其中使用多個叢集和內容的Kbeconfig。請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["知識庫文章"^] 以取得更多資訊。



== 透過Cloud Insights Proxy連線時、託管叢集不會出現在NetApp的整個過程中

當Astra Control Center Cloud Insights 透過Proxy連線至NetApp功能時、受管理的叢集可能不會出現在Cloud Insights 畫面上。因應措施是在每個託管叢集上執行下列命令：

[source, console]
----
kubectl get cm telegraf-conf -o yaml -n netapp-monitoring | sed '/\[\[outputs.http\]\]/c\    [[outputs.http]]\n    use_system_proxy = true' | kubectl replace -f -
----
[source, console]
----
kubectl get cm telegraf-conf-rs -o yaml -n netapp-monitoring | sed '/\[\[outputs.http\]\]/c\    [[outputs.http]]\n    use_system_proxy = true' | kubectl replace -f -
----
[source, console]
----
kubectl get pods -n netapp-monitoring --no-headers=true | grep 'telegraf-ds\|telegraf-rs' | awk '{print $1}' | xargs kubectl delete -n netapp-monitoring pod
----


== 當Astra Trident離線時、應用程式資料管理作業會因內部服務錯誤（500）而失敗

如果應用程式叢集上的Astra Trident離線（並重新連線）、而且在嘗試應用程式資料管理時遇到500個內部服務錯誤、請重新啟動應用程式叢集中的所有Kubernetes節點、以還原功能。



== 如需詳細資訊、請參閱

* link:../release-notes/known-limitations.html["已知限制"]

